In [24]:
import json
import os
import pandas as pd
import re
import shutil
from collections import defaultdict
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from functions import *
from eval_functions import *

In [25]:
main_directory = 'model_output'
models = find_folders_with_output(main_directory)

save = True

eval_path = f"evaluate/batch1"
os.makedirs(eval_path, exist_ok=True)

### Model Output to nice JSON and Failure

In [20]:
def process_files(model, save=save):
    input_dir = f"model_output/{model}/output/"
    output_dir = f"model_output/{model}/formatted/"
    failure_dir = f"model_output/{model}/failed/"
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(failure_dir, exist_ok=True)
    files = os.listdir(input_dir)
    len_files = len(files)
    for filename in files:
        if filename.endswith('.json'):
            input_file_path = os.path.join(input_dir, filename)
            output_file_path = os.path.join(output_dir, filename)
            failure_file_path = os.path.join(failure_dir, filename)
            try:
                file = read_json(input_file_path)
                print(f"Processing file: {filename}")
                if save:
                    shutil.copy(input_file_path, output_file_path)
                    #save_json_to_file(file, output_file_path)
            except Exception as e:
                print(f"Error processing file {filename}: {e}")
                if save:
                    shutil.copy(input_file_path, failure_file_path)
    return len_files

In [21]:
for model in models:
    print(model)
    # 1 - Preprocess Files
    num_out_files = process_files(model, save=save)
    print(num_out_files)
    # 2 - Evaluate Files
    p2_label_path = "chia_label/p2"
    ready_path = f"model_output/{model}/ready"
    failed_model_path = f"model_output/{model}/failed_inner"
    p2_model_formatted_path = f"model_output/{model}/formatted"
    
    for path in [ready_path, failed_model_path, p2_model_formatted_path]:
        os.makedirs(path, exist_ok=True)
    
    label_files = {extract_nct_number(f): os.path.join(p2_label_path, f) for f in os.listdir(p2_label_path) if f.endswith('.json')}
    model_files = {extract_nct_number(f): os.path.join(p2_model_formatted_path, f) for f in os.listdir(p2_model_formatted_path) if f.endswith('.json')}
    
    common_ncts = set(label_files.keys()).intersection(model_files.keys())
    labels = []
    predictions = []
    success_data = []
    
    for nct in common_ncts:
        try:
            label_data = read_json(label_files[nct])
            model_data = read_json(model_files[nct])
            print(model_data)
            label_structure = extract_logical_structure(label_data)
            model_structure = extract_logical_structure(model_data)
    
            # Try count words
            label_raw_texts = extract_raw_texts(label_data)
            model_raw_texts = extract_raw_texts(model_data)
            
            missing_texts = label_raw_texts - model_raw_texts
            
            label_words = extract_words(label_raw_texts)
            model_words = extract_words(model_raw_texts)
            missing_words = label_words - model_words
            missing_words_pct = len(missing_words) / len(label_words) * 100 if label_words else 0
            print(f"Processing NCT {nct}")
            print(round(missing_words_pct,2), "%")
            print(label_words.issubset(model_words))
            print("Label Text \n")
            print(label_words)
            print("\nModel Text \n")
            print(model_words)
            print()
            
            success_data.append({
                'NCT': nct,
                'label_AND': label_structure.get('AND', 0),
                'label_OR': label_structure.get('OR', 0),
                'label_NOT': label_structure.get('NOT', 0),
                'label_DEPTH': label_structure.get('depth', 0),
                'model_AND': model_structure.get('AND', 0),
                'model_OR': model_structure.get('OR', 0),
                'model_NOT': model_structure.get('NOT', 0),
                'model_DEPTH': model_structure.get('depth', 0),
                'diff_AND': 1 if model_structure.get('AND', 0) > label_structure.get('AND', 0) else -1 if model_structure.get('AND', 0) < label_structure.get('AND', 0) else 0,
                'diff_OR': 1 if model_structure.get('OR', 0) > label_structure.get('OR', 0) else -1 if model_structure.get('OR', 0) < label_structure.get('OR', 0) else 0,
                'diff_NOT': 1 if model_structure.get('NOT', 0) > label_structure.get('NOT', 0) else -1 if model_structure.get('NOT', 0) < label_structure.get('NOT', 0) else 0,
                'diff_DEPTH': 1 if model_structure.get('depth', 0) > label_structure.get('depth', 0) else -1 if model_structure.get('depth', 0) < label_structure.get('depth', 0) else 0,
                'num_out_files': num_out_files,
            })
    
            labels.append(label_structure)
            predictions.append(model_structure)
            save and shutil.copy(model_files[nct], os.path.join(ready_path, os.path.basename(model_files[nct])))
        except Exception as e:
            #print(f"Error processing NCT {nct}: {e}")
            save and shutil.copy(model_files[nct], os.path.join(failed_model_path, os.path.basename(model_files[nct])))
    
    df_success = pd.DataFrame(success_data).set_index('NCT')
    df_success.to_csv(eval_path+f'/{model}_eval.csv')
    true_values = df_success[['label_AND', 'label_OR', 'label_NOT', 'label_DEPTH']].values
    predicted_values = df_success[['model_AND', 'model_OR', 'model_NOT', 'model_DEPTH']].values
    
    metrics = {}
    for i, metric in enumerate(['AND', 'OR', 'NOT', 'DEPTH']):
        y_true = true_values[:, i]
        y_pred = predicted_values[:, i]
    
        diffs = y_pred - y_true
        pct_greater = (diffs > 0).sum() / len(diffs) * 100
        pct_less = (diffs < 0).sum() / len(diffs) * 100
        pct_equal = (diffs == 0).sum() / len(diffs) * 100
    
        metrics[metric] = {
            'accuracy': round(accuracy_score(y_true, y_pred), 3),
            'precision': round(precision_score(y_true, y_pred, average='weighted', zero_division=0), 3),
            'recall': round(recall_score(y_true, y_pred, average='weighted', zero_division=0), 3),
            'f1_score': round(f1_score(y_true, y_pred, average='weighted', zero_division=0), 3),
            'pct_greater': round(pct_greater, 2),
            'pct_less': round(pct_less, 2),
            'pct_equal': round(pct_equal, 2)
            # 'confusion_matrix': confusion_matrix(y_true, y_pred)
        }
        metrics_df = pd.DataFrame(metrics).T
        num_nct_files = len(df_success)
        metrics_df['num_nct_files'] = num_nct_files
        metrics_df['model_name'] = model
        metrics_df['num_files'] = anzahl_files
        # Save Metrics to CSV
        metrics_df.to_csv(os.path.join(eval_path, f'{model}_metrics_summary.csv'))

Llama-3-8B-Instruct-Gradient-1048k_25_shot
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00846703_inc_25_shot.json: Expecting ',' delimiter: line 69 column 2 (char 2291)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00862446_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00862446_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00867958_exc_25_shot.json: Expecting ',' delimiter: line 45 column 2 (char 1542)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00867958_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00886158_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00886158_inc_25_shot.json: Expecting ',' delimiter: line 22 column 2 (char 499)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00894712_exc_25_shot.json: Expecting ',' delimiter: line 38 column 2 (char 1003)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00894712_inc_25_shot.json: Expecting ',' delimiter: line 54 column 2 (char 1999)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00904202_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00904202_inc_25_shot.json: Expecting ',' delimiter: line 58 column 2 (char 2250)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00917891_exc_25_shot.json: Expecting ',' delimiter: line 113 column 2 (char 3592)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00917891_inc_25_shot.json: Expecting ',' delimiter: line 91 column 2 (char 3599)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00926523_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00926523_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00931983_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00931983_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00943865_exc_25_shot.json: Expecting ',' delimiter: line 75 column 2 (char 1933)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00943865_inc_25_shot.json: Expecting ',' delimiter: line 59 column 2 (char 1690)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00954850_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00954850_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00959569_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00959569_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00962364_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00962364_inc_25_shot.json: Expecting ',' delimiter: line 24 column 2 (char 633)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00965900_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00965900_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00970866_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00970866_inc_25_shot.json: Expecting ',' delimiter: line 67 column 2 (char 2377)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00989261_exc_25_shot.json: Expecting ',' delimiter: line 168 column 2 (char 6003)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00989261_inc_25_shot.json: Expecting property name enclosed in double quotes: line 27 column 9 (char 861)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00994786_exc_25_shot.json: Expecting ',' delimiter: line 151 column 2 (char 5578)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00994786_inc_25_shot.json: Expecting ',' delimiter: line 50 column 2 (char 2207)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01000155_exc_25_shot.json: Expecting ',' delimiter: line 118 column 2 (char 3624)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01000155_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01009359_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01009359_inc_25_shot.json: Expecting ',' delimiter: line 48 column 2 (char 1260)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01032109_exc_25_shot.json: Expecting ',' delimiter: line 38 column 2 (char 980)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01032109_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01051414_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01051414_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01064752_exc_25_shot.json: Expecting ',' delimiter: line 67 column 2 (char 1884)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01064752_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01078051_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01078051_inc_25_shot.json: Expecting ',' delimiter: line 100 column 2 (char 2673)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01082549_exc_25_shot.json: Expecting ',' delimiter: line 107 column 2 (char 4212)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01082549_inc_25_shot.json: Expecting ',' delimiter: line 71 column 2 (char 4280)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01084993_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01084993_inc_25_shot.json: Expecting ',' delimiter: line 58 column 2 (char 1777)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01088750_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01088750_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01098383_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01098383_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01116882_exc_25_shot.json: Expecting ',' delimiter: line 171 column 2 (char 5988)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01116882_inc_25_shot.json: Expecting ',' delimiter: line 73 column 2 (char 4434)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01116973_exc_25_shot.json: Expecting ',' delimiter: line 72 column 2 (char 1875)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01116973_inc_25_shot.json: Expecting ',' delimiter: line 38 column 2 (char 1114)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01117181_exc_25_shot.json: Expecting ',' delimiter: line 126 column 2 (char 5671)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01117181_inc_25_shot.json: Extra data: line 49 column 1 (char 2852)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01118871_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01118871_inc_25_shot.json: Expecting ',' delimiter: line 123 column 2 (char 3730)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01175044_exc_25_shot.json: Expecting ',' delimiter: line 51 column 2 (char 1311)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01175044_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01177891_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01177891_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01184638_exc_25_shot.json: Expecting ',' delimiter: line 33 column 2 (char 639)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01184638_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01205334_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01205334_inc_25_shot.json: Expecting ',' delimiter: line 90 column 2 (char 2726)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01214096_exc_25_shot.json: Expecting ',' delimiter: line 178 column 2 (char 5602)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01214096_inc_25_shot.json: Expecting ',' delimiter: line 45 column 2 (char 1496)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01217671_exc_25_shot.json: Expecting ',' delimiter: line 130 column 2 (char 3910)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01217671_inc_25_shot.json: Expecting ',' delimiter: line 116 column 2 (char 4727)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01218737_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01218737_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01228279_exc_25_shot.json: Expecting ',' delimiter: line 125 column 2 (char 3288)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01228279_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01236417_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01236417_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01261832_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01261832_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01312012_exc_25_shot.json: Expecting ',' delimiter: line 36 column 2 (char 922)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01312012_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01313676_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01313676_inc_25_shot.json: Expecting ',' delimiter: line 50 column 2 (char 2560)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01314898_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01314898_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01320579_exc_25_shot.json: Extra data: line 118 column 1 (char 3791)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01320579_inc_25_shot.json: Expecting ',' delimiter: line 66 column 2 (char 1843)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01322464_exc_25_shot.json: Expecting ',' delimiter: line 94 column 2 (char 3782)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01322464_inc_25_shot.json: Expecting ',' delimiter: line 62 column 2 (char 2923)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01346436_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01346436_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01349413_exc_25_shot.json: Expecting ',' delimiter: line 63 column 2 (char 1512)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01349413_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01352598_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01352598_inc_25_shot.json: Expecting ',' delimiter: line 86 column 2 (char 3468)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01373684_exc_25_shot.json: Expecting ',' delimiter: line 116 column 2 (char 3741)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01373684_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01391780_exc_25_shot.json: Expecting ',' delimiter: line 38 column 2 (char 866)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01391780_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01401335_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01401335_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01410890_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01410890_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01424020_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01424020_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01440296_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01440296_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01446094_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01446094_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01483118_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01483118_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01490034_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01490034_inc_25_shot.json: Expecting ',' delimiter: line 63 column 2 (char 2251)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01491295_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01491295_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01491763_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01491763_inc_25_shot.json: Expecting ',' delimiter: line 24 column 2 (char 1179)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01497639_exc_25_shot.json: Extra data: line 34 column 1 (char 1008)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01497639_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01501201_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01501201_inc_25_shot.json: Expecting ',' delimiter: line 33 column 2 (char 667)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01518946_exc_25_shot.json: Expecting ',' delimiter: line 69 column 2 (char 3322)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01518946_inc_25_shot.json: Expecting ',' delimiter: line 31 column 2 (char 1235)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01531257_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01531257_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01567605_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01567605_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01579604_exc_25_shot.json: Expecting ',' delimiter: line 64 column 2 (char 1422)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01579604_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01581749_exc_25_shot.json: Expecting ',' delimiter: line 29 column 2 (char 761)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01581749_inc_25_shot.json: Expecting ',' delimiter: line 38 column 2 (char 1034)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01602081_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01602081_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01604187_exc_25_shot.json: Expecting ',' delimiter: line 75 column 2 (char 2129)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01604187_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01614041_exc_25_shot.json: Expecting ',' delimiter: line 94 column 2 (char 4274)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01614041_inc_25_shot.json: Expecting ',' delimiter: line 49 column 2 (char 1118)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01630954_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01630954_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01631058_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01631058_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01639664_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01639664_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01642875_exc_25_shot.json: Expecting ',' delimiter: line 71 column 2 (char 1644)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01642875_inc_25_shot.json: Extra data: line 24 column 1 (char 457)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01650792_exc_25_shot.json: Expecting ',' delimiter: line 45 column 2 (char 1404)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01650792_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01664507_exc_25_shot.json: Expecting ',' delimiter: line 38 column 2 (char 898)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01664507_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01665417_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01665417_inc_25_shot.json: Extra data: line 54 column 1 (char 1357)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01669369_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01669369_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01680081_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01680081_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01684501_exc_25_shot.json: Expecting ',' delimiter: line 57 column 2 (char 1733)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01684501_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01696617_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01696617_inc_25_shot.json: Expecting ',' delimiter: line 41 column 2 (char 1464)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01700790_exc_25_shot.json: Expecting ',' delimiter: line 80 column 2 (char 3728)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01700790_inc_25_shot.json: Expecting ',' delimiter: line 68 column 2 (char 2609)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01701219_exc_25_shot.json: Expecting ',' delimiter: line 81 column 2 (char 2490)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01701219_inc_25_shot.json: Expecting ',' delimiter: line 47 column 2 (char 1397)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01709981_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01709981_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01711801_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01711801_inc_25_shot.json: Expecting ',' delimiter: line 28 column 2 (char 1087)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01715584_exc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01715584_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01715714_exc_25_shot.json: Expecting ',' delimiter: line 45 column 2 (char 1225)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01715714_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01717911_exc_25_shot.json: Expecting ',' delimiter: line 60 column 2 (char 1502)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01717911_inc_25_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01720394_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01720394_inc_25_shot.json: Expecting ',' delimiter: line 62 column 2 (char 1979)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01728194_exc_25_shot.json: Expecting ',' delimiter: line 101 column 2 (char 3141)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01728194_inc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01735955_exc_25_shot.json: Expecting ',' delimiter: line 46 column 2 (char 1966)
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01735955_inc_25_shot.json: Expecting ',' delimiter: line 38 column 2 (char 1341)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01742117_exc_25_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01742117_inc_25_shot.json: Expecting ',' delimiter: line 82 column 2 (char 2374)
183

In [22]:
# NCT02935855_inc

In [23]:
df_success = pd.DataFrame(success_data).set_index('NCT')
df_success.to_csv(eval_path+f'/{model}_eval.csv')

df_success

,label_AND,label_OR,label_NOT,label_DEPTH,model_AND,model_OR,model_NOT,model_DEPTH,diff_AND,diff_OR,diff_NOT,diff_DEPTH,num_out_files
NCT,,,,,,,,,,,,,
NCT01680081_inc,3,1,0,7,2,1,0,5,-1,0,0,-1,300
NCT01728194_inc,7,1,0,11,4,0,0,8,-1,-1,0,-1,300
NCT00050349_exc,21,18,3,33,7,12,3,19,-1,-1,0,-1,300
NCT01084993_exc,3,3,1,11,4,1,1,9,1,-1,0,-1,300
NCT01000155_exc,15,8,3,33,10,9,0,19,-1,1,-1,-1,300
...,...,...,...,...,...,...,...,...,...,...,...,...,...
NCT01567605_exc,11,5,2,23,3,3,0,9,-1,-1,-1,-1,300
NCT01175044_inc,1,0,0,3,1,0,0,3,0,0,0,0,300
NCT00440245_inc,1,1,0,5,0,1,0,3,-1,0,0,-1,300
NCT00397215_inc,4,2,0,11,6,1,0,11,1,-1,0,0,300
NCT01373684_exc,19,21,2,41,3,3,0,9,-1,-1,-1,-1,300

In [18]:
true_values = df_success[['label_AND', 'label_OR', 'label_NOT', 'label_DEPTH']].values
predicted_values = df_success[['model_AND', 'model_OR', 'model_NOT', 'model_DEPTH']].values

metrics = {}
for i, metric in enumerate(['AND', 'OR', 'NOT', 'DEPTH']):
    y_true = true_values[:, i]
    y_pred = predicted_values[:, i]

    diffs = y_pred - y_true
    pct_greater = (diffs > 0).sum() / len(diffs) * 100
    pct_less = (diffs < 0).sum() / len(diffs) * 100
    pct_equal = (diffs == 0).sum() / len(diffs) * 100


    metrics[metric] = {
        'accuracy': round(accuracy_score(y_true, y_pred), 3),
        'precision': round(precision_score(y_true, y_pred, average='weighted', zero_division=0), 3),
        'recall': round(recall_score(y_true, y_pred, average='weighted', zero_division=0), 3),
        'f1_score': round(f1_score(y_true, y_pred, average='weighted', zero_division=0), 3),
        'pct_greater': round(pct_greater, 2),
        'pct_less': round(pct_less, 2),
        'pct_equal': round(pct_equal, 2)
       # 'confusion_matrix': confusion_matrix(y_true, y_pred)
    }
    metrics_df = pd.DataFrame(metrics).T  
    num_nct_files = len(df_success)
    metrics_df['num_out_files'] = num_nct_files
    metrics_df['num_nct_files'] = num_nct_files
    metrics_df['model_name'] = model
    # Save Metrics to CSV
    metrics_df.to_csv(os.path.join(eval_path, f'{model}_metrics_summary.csv'))

print(f"{len(df_success)} Daten mit {model}")
for metric, values in metrics.items():
    print(f"Metrics for {metric}:")
    print(f"  Accuracy: {values['accuracy']}")
    print(f"  Precision: {values['precision']}")
    print(f"  Recall: {values['recall']}")
    print(f"  F1 Score: {values['f1_score']}")

    print(f"  % Greater: {values['pct_greater']}")
    print(f"  % Less: {values['pct_less']}")
    print(f"  % Equal: {values['pct_equal']}")
    print()
    #print(f"  Confusion Matrix:\n{values['confusion_matrix']}\n")

264 Daten mit Llama-3-8B-Instruct_4_shot_temp_1
Metrics for AND:
  Accuracy: 0.121
  Precision: 0.102
  Recall: 0.121
  F1 Score: 0.103
  % Greater: 17.8
  % Less: 70.08
  % Equal: 12.12

Metrics for OR:
  Accuracy: 0.246
  Precision: 0.277
  Recall: 0.246
  F1 Score: 0.256
  % Greater: 42.05
  % Less: 33.33
  % Equal: 24.62

Metrics for NOT:
  Accuracy: 0.625
  Precision: 0.571
  Recall: 0.625
  F1 Score: 0.579
  % Greater: 9.85
  % Less: 27.65
  % Equal: 62.5

Metrics for DEPTH:
  Accuracy: 0.121
  Precision: 0.109
  Recall: 0.121
  F1 Score: 0.105
  % Greater: 15.53
  % Less: 72.35
  % Equal: 12.12

In [19]:
matching_rows = df_success[df_success['label_AND'] == df_success['model_AND']][['label_AND', 'model_AND']]
matching_rows

                 label_AND  model_AND
NCT
NCT00718952_inc          7          7
NCT00480129_inc          2          2
NCT01501201_inc          4          4
NCT01391780_inc          1          1
NCT00846703_exc          6          6
NCT00787254_inc          2          2
NCT00404495_exc          3          3
NCT00425789_inc          3          3
NCT00959569_inc          3          3
NCT00250640_inc          5          5
NCT01567605_inc          2          2
NCT00425789_exc          1          1
NCT00806936_inc          2          2
NCT01116973_inc          5          5
NCT00050349_inc         10         10
NCT01424020_inc          4          4
NCT01518946_inc          6          6
NCT01709981_inc          1          1
NCT01491295_inc          3          3
NCT00305097_exc          4          4
NCT01717911_exc          9          9
NCT00401245_exc          4          4
NCT01032109_inc          4          4
NCT00279552_exc          1          1
NCT00752310_inc          6          6
NCT01088750_inc          3          3
NCT01051414_inc          2          2
NCT01440296_exc          1          1
NCT01401335_exc          1          1
NCT01228279_inc          2          2
NCT00317148_inc          3          3
NCT01175044_inc          1          1