In [1]:
import json
import os
import pandas as pd
import re
import shutil
from collections import defaultdict
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from functions import *

In [2]:
model = "Llama-3-8B-Instruct-Gradient-1048k_10_shot"#"Llama-3-8B-Instruct_4_shot"

### Model Output to nice JSON and Failure

In [3]:
input_dir = f"model_output/{model}/output/"
output_dir = f"model_output/{model}/formatted/"
failure_dir = f"model_output/{model}/failed/"

if not os.path.exists(output_dir):
    os.makedirs(output_dir)
if not os.path.exists(failure_dir):
    os.makedirs(failure_dir)

for filename in os.listdir(input_dir):
    if filename.endswith('.json'):
        input_file_path = os.path.join(input_dir, filename)
        output_file_path = os.path.join(output_dir, filename)
        failure_file_path = os.path.join(failure_dir, filename)
        try:
            file = read_json(input_file_path)
            print(f"Processing file: {filename}")
            save_json_to_file(file, output_file_path)
        except Exception as e:
            print(f"Error processing file {filename}: {e}")
            shutil.move(input_file_path, failure_file_path)

Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00050349_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00050349_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00061308_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00061308_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00094861_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00183885_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00183885_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00198913_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00198913_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00235170_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00235170_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00236340_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00236340_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00250640_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00250640_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00279552_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00279552_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00305097_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00305097_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00312429_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00312429_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00317148_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00317148_inc_10_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00319748_exc_10_shot.json: Invalid control character at: line 1 column 4571 (char 4570)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00319748_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00324363_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00324363_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00343668_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00343668_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00344318_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00344318_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00351611_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00351611_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00356148_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00356148_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00379366_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00379366_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00391690_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00391690_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00396734_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00396734_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00397215_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00397215_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00401245_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00401245_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00404495_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00404495_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00425789_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00425789_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00426751_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00426751_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00440245_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00440245_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00445029_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00445029_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00455663_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00455663_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00461136_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00461136_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00480129_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00480129_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00483106_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00483106_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00500500_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00500500_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00502567_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00502567_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00527826_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00527826_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00543712_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00543712_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00576173_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00576173_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00586898_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00586898_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00599924_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00599924_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00609531_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00609531_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00625742_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00625742_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00639795_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00639795_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00650312_exc_10_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00650312_inc_10_shot.json: Extra data: line 1 column 2530 (char 2529)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00676273_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00676273_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00679341_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00679341_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00718952_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00718952_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00720031_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00720031_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00728156_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00728156_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00730301_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00730301_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00749112_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00749112_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00752310_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00752310_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00785213_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00785213_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00787254_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00787254_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00806273_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00806273_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00806936_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00806936_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00812344_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00812344_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00846703_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00846703_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00862446_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00862446_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00867958_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00867958_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00886158_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00886158_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00894712_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00894712_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00904202_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00904202_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00917891_exc_10_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT00917891_inc_10_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00926523_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00926523_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00931983_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00931983_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00943865_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00943865_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00954850_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00954850_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00959569_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00959569_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00962364_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00962364_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00965900_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00965900_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00970866_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00970866_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00989261_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00989261_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00994786_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT00994786_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01000155_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01000155_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01009359_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01009359_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01032109_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01032109_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01051414_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01051414_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01064752_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01064752_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01078051_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01078051_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01082549_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01082549_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01084993_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01084993_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01088750_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01088750_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01098383_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01098383_inc_10_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01116882_exc_10_shot.json: Invalid control character at: line 1 column 4750 (char 4749)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01116882_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01116973_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01116973_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01117181_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01117181_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01118871_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01118871_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01175044_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01175044_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01177891_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01177891_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01184638_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01184638_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01205334_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01205334_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01214096_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01214096_inc_10_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01217671_exc_10_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01217671_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01218737_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01218737_inc_10_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01228279_exc_10_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01228279_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01236417_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01236417_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01261832_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01261832_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01312012_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01312012_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01313676_exc_10_shot.json
Error processing file Llama-3-8B-Instruct-Gradient-1048k_NCT01313676_inc_10_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01314898_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01314898_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01320579_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01320579_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01322464_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01322464_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01346436_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01346436_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01349413_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01349413_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01352598_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01352598_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01373684_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01373684_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01391780_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01391780_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01401335_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01401335_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01410890_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01410890_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01424020_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01424020_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01440296_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01440296_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01446094_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01446094_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01483118_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01483118_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01490034_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01490034_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01491295_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01491295_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01491763_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01491763_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01497639_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01497639_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01501201_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01501201_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01518946_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01518946_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01531257_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01531257_inc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01567605_exc_10_shot.json
Processing file: Llama-3-8B-Instruct-Gradient-1048k_NCT01567605_inc_10_shot.json

In [4]:
p2_label_path = "chia_label/p2"
ready_path = f"model_output/{model}/ready"
failed_model_path = f"model_output/{model}/failed_inner"
p2_model_formatted_path = f"model_output/{model}/formatted"
eval_path = f"evaluate/batch1"

for path in [ready_path, failed_model_path, p2_model_formatted_path]: 
    os.makedirs(path, exist_ok=True)

In [5]:
def extract_nct_number(filename):
    parts = filename.split('_')
    nct_number = None
    file_type = None
    for part in parts:
        if part.startswith("NCT"):
            nct_number = part
        if part in ["inc", "exc"]:
            file_type = part
    return nct_number+"_"+file_type


def extract_logical_structure(data):
    structure = defaultdict(int)
    def traverse(node, depth=0):
        nonlocal structure
        structure["depth"] = max(structure["depth"], depth)

        if isinstance(node, dict):
            for key in node:
                if key in ["AND", "OR", "NOT"]:
                    structure[key] += 1
                traverse(node[key], depth + 1)
        elif isinstance(node, list):
            for item in node:
                traverse(item, depth + 1)

    traverse(data)
    return dict(structure)

def extract_raw_texts(data):
    raw_texts = set()
    def traverse(node):
        if isinstance(node, dict):
            for key, value in node.items():
                if key == "raw_text":
                    raw_texts.add(value)
                else:
                    traverse(value)
        elif isinstance(node, list):
            for item in node:
                traverse(item)

    traverse(data)
    return raw_texts

def extract_words(raw_texts):
    words = set()
    for text in raw_texts:
        words.update(text.split())
    return words

In [6]:
label_files = {extract_nct_number(f): os.path.join(p2_label_path, f) for f in os.listdir(p2_label_path) if f.endswith('.json')}
model_files = {extract_nct_number(f): os.path.join(p2_model_formatted_path, f) for f in os.listdir(p2_model_formatted_path) if f.endswith('.json')}

common_ncts = set(label_files.keys()).intersection(model_files.keys())

In [7]:
labels = []
predictions = []
success_data = []

In [9]:
for nct in common_ncts:# ["NCT00050349_exc"]
    try:
        label_data = read_json(label_files[nct])
        model_data = read_json(model_files[nct])
        label_structure = extract_logical_structure(label_data)
        model_structure = extract_logical_structure(model_data)

        # Try count words
        label_raw_texts = extract_raw_texts(label_data)
        model_raw_texts = extract_raw_texts(model_data)
        missing_texts = label_raw_texts - model_raw_texts
        label_words = extract_words(label_raw_texts)
        model_words = extract_words(model_raw_texts)
        missing_words = label_words - model_words
        missing_words_pct = len(missing_words) / len(label_words) * 100 if label_words else 0
        print(missing_words_pct)
        
        success_data.append({
            'NCT': nct,
            'label_AND': label_structure.get('AND', 0),
            'label_OR': label_structure.get('OR', 0),
            'label_NOT': label_structure.get('NOT', 0),
            'label_DEPTH': label_structure.get('depth', 0),
            'model_AND': model_structure.get('AND', 0),
            'model_OR': model_structure.get('OR', 0),
            'model_NOT': model_structure.get('NOT', 0),
            'model_DEPTH': model_structure.get('depth', 0),
            'diff_AND': 1 if model_structure.get('AND', 0) > label_structure.get('AND', 0) else -1 if model_structure.get('AND', 0) < label_structure.get('AND', 0) else 0,
            'diff_OR': 1 if model_structure.get('OR', 0) > label_structure.get('OR', 0) else -1 if model_structure.get('OR', 0) < label_structure.get('OR', 0) else 0,
            'diff_NOT': 1 if model_structure.get('NOT', 0) > label_structure.get('NOT', 0) else -1 if model_structure.get('NOT', 0) < label_structure.get('NOT', 0) else 0,
            'diff_DEPTH': 1 if model_structure.get('depth', 0) > label_structure.get('depth', 0) else -1 if model_structure.get('depth', 0) < label_structure.get('depth', 0) else 0
            
        })

        labels.append(label_structure)
        predictions.append(model_structure)
        shutil.copy(model_files[nct], os.path.join(ready_path, os.path.basename(model_files[nct])))
    except Exception as e:
        print(f"Error processing NCT {nct}: {e}")
        shutil.copy(model_files[nct], os.path.join(failed_model_path, os.path.basename(model_files[nct])))

Error processing NCT NCT02041299_inc: Expecting ',' delimiter: line 37 column 2 (char 1291)
Error processing NCT NCT02055053_exc: Expecting ',' delimiter: line 32 column 2 (char 644)
Error processing NCT NCT02773173_inc: Expecting ',' delimiter: line 31 column 2 (char 717)
Error processing NCT NCT02277067_exc: Expecting ',' delimiter: line 17 column 2 (char 421)
0.0
Error processing NCT NCT02653131_inc: Expecting ',' delimiter: line 20 column 2 (char 402)
8.695652173913043
0.0
Error processing NCT NCT02701777_inc: Extra data: line 85 column 1 (char 2530)
Error processing NCT NCT00959569_inc: Expecting ',' delimiter: line 20 column 2 (char 359)
Error processing NCT NCT01088750_inc: Expecting ',' delimiter: line 24 column 2 (char 384)
0.0
0.0
Error processing NCT NCT02607748_inc: Expecting ',' delimiter: line 42 column 2 (char 1793)
3.125
0.0
Error processing NCT NCT02787863_inc: Expecting ',' delimiter: line 49 column 2 (char 2253)
Error processing NCT NCT02926989_exc: Extra data: line 72 column 3 (char 2682)
10.0
17.307692307692307
9.75609756097561
Error processing NCT NCT02243553_exc: Expecting ',' delimiter: line 110 column 2 (char 5093)
Error processing NCT NCT02920177_exc: Extra data: line 98 column 1 (char 3749)
Error processing NCT NCT02464865_inc: Expecting ',' delimiter: line 13 column 2 (char 234)
16.0
12.0
Error processing NCT NCT02790593_exc: Expecting ',' delimiter: line 59 column 2 (char 2088)
Error processing NCT NCT02731794_inc: Expecting ',' delimiter: line 24 column 2 (char 507)
Error processing NCT NCT02942303_exc: Expecting ',' delimiter: line 84 column 2 (char 2667)
0.0
Error processing NCT NCT02732080_inc: Expecting ',' delimiter: line 6 column 2 (char 276)
Error processing NCT NCT01701219_exc: Expecting ',' delimiter: line 63 column 2 (char 2760)
0.0
0.0
Error processing NCT NCT02441179_inc: Expecting ',' delimiter: line 6 column 57 (char 115)
1.9607843137254901
Error processing NCT NCT02707874_exc: Expecting ',' delimiter: line 71 column 2 (char 2681)
0.0
Error processing NCT NCT02982577_inc: Expecting ',' delimiter: line 39 column 2 (char 1242)
Error processing NCT NCT02874092_exc: Expecting ',' delimiter: line 96 column 2 (char 5805)
Error processing NCT NCT02003339_inc: Expecting ',' delimiter: line 47 column 2 (char 1602)
16.666666666666664
7.2727272727272725
Error processing NCT NCT02954029_inc: Expecting ',' delimiter: line 13 column 2 (char 246)
Error processing NCT NCT01639664_exc: Expecting ',' delimiter: line 45 column 2 (char 1271)
Error processing NCT NCT01815580_exc: Expecting ',' delimiter: line 55 column 2 (char 2322)
0.0
Error processing NCT NCT02726009_inc: Expecting ',' delimiter: line 56 column 2 (char 2049)
0.0
Error processing NCT NCT02627521_exc: Extra data: line 38 column 1 (char 881)
Error processing NCT NCT02035904_inc: Expecting ',' delimiter: line 37 column 2 (char 1132)
4.545454545454546
8.88888888888889
0.0
4.545454545454546
0.0
13.636363636363635
0.0
0.0
Error processing NCT NCT02638935_exc: Expecting ',' delimiter: line 56 column 2 (char 1998)
Error processing NCT NCT01743755_inc: Expecting ',' delimiter: line 76 column 2 (char 2039)
0.0
Error processing NCT NCT02429765_inc: Expecting ',' delimiter: line 21 column 87 (char 733)
4.25531914893617
Error processing NCT NCT00396734_inc: Expecting ',' delimiter: line 6 column 2 (char 148)
Error processing NCT NCT02621541_exc: Expecting ',' delimiter: line 6 column 2 (char 227)
Error processing NCT NCT00728156_exc: Extra data: line 69 column 1 (char 2626)
14.285714285714285
0.0
0.0
Error processing NCT NCT02673359_exc: Expecting ',' delimiter: line 59 column 2 (char 1683)
10.0
0.0
25.0
73.91304347826086
7.6923076923076925
Error processing NCT NCT02318446_inc: Expecting ',' delimiter: line 28 column 2 (char 1004)
Error processing NCT NCT02732080_exc: Extra data: line 29 column 1 (char 758)
Error processing NCT NCT02901106_exc: Expecting ',' delimiter: line 24 column 2 (char 433)
Error processing NCT NCT02707809_exc: Expecting ',' delimiter: line 28 column 2 (char 583)
Error processing NCT NCT02509091_inc: Expecting ',' delimiter: line 57 column 2 (char 1901)
Error processing NCT NCT02874092_inc: Expecting ',' delimiter: line 16 column 2 (char 470)
Error processing NCT NCT00926523_inc: Expecting ',' delimiter: line 24 column 2 (char 592)
Error processing NCT NCT01313676_exc: Expecting ',' delimiter: line 121 column 2 (char 6008)
Error processing NCT NCT02746900_inc: Expecting ',' delimiter: line 20 column 2 (char 341)
0.0
Error processing NCT NCT02974660_inc: Expecting ',' delimiter: line 42 column 2 (char 1108)
0.0
Error processing NCT NCT01650792_exc: Expecting ',' delimiter: line 44 column 2 (char 1223)
Error processing NCT NCT02535299_exc: Expecting ',' delimiter: line 24 column 2 (char 632)
Error processing NCT NCT00543712_exc: Extra data: line 99 column 1 (char 5440)
26.666666666666668
Error processing NCT NCT02924870_inc: Expecting ',' delimiter: line 31 column 2 (char 836)
Error processing NCT NCT00356148_exc: Expecting ',' delimiter: line 58 column 2 (char 1846)
Error processing NCT NCT01214096_exc: Expecting ',' delimiter: line 119 column 21 (char 4123)
Error processing NCT NCT01803438_inc: Expecting ',' delimiter: line 53 column 2 (char 1844)
3.571428571428571
Error processing NCT NCT01098383_exc: Extra data: line 89 column 11 (char 3916)
0.0
Error processing NCT NCT01891513_exc: Expecting ',' delimiter: line 93 column 2 (char 5899)
0.0
Error processing NCT NCT00931983_inc: Expecting ',' delimiter: line 35 column 2 (char 988)
10.416666666666668
Error processing NCT NCT02601157_exc: Expecting ',' delimiter: line 7 column 2 (char 1050)
0.0
0.0
Error processing NCT NCT02527512_inc: Expecting ',' delimiter: line 16 column 2 (char 341)
Error processing NCT NCT02251249_exc: Expecting ',' delimiter: line 68 column 2 (char 2350)
Error processing NCT NCT01518946_inc: Expecting ',' delimiter: line 31 column 2 (char 1247)
Error processing NCT NCT01997112_exc: Extra data: line 31 column 1 (char 933)
5.0
37.5
Error processing NCT NCT02689024_inc: Expecting ',' delimiter: line 13 column 2 (char 229)
Error processing NCT NCT02431442_exc: Expecting ':' delimiter: line 95 column 85 (char 7662)
Error processing NCT NCT02805504_exc: Expecting ',' delimiter: line 31 column 2 (char 724)
Error processing NCT NCT01669369_inc: Expecting ',' delimiter: line 27 column 2 (char 603)
Error processing NCT NCT02760459_exc: Extra data: line 91 column 9 (char 4292)
Error processing NCT NCT02810704_exc: Expecting ',' delimiter: line 82 column 2 (char 3613)
Error processing NCT NCT02964416_exc: Expecting ',' delimiter: line 69 column 2 (char 1940)
Error processing NCT NCT02894645_exc: Expecting ',' delimiter: line 51 column 2 (char 1293)
Error processing NCT NCT02369211_exc: Expecting ',' delimiter: line 45 column 2 (char 1164)
0.0
0.0
0.0
7.142857142857142
Error processing NCT NCT00455663_exc: Expecting ',' delimiter: line 24 column 2 (char 596)
Error processing NCT NCT02802644_exc: Expecting ',' delimiter: line 120 column 2 (char 3846)
Error processing NCT NCT02689089_exc: Expecting ',' delimiter: line 94 column 2 (char 2737)
Error processing NCT NCT02379156_inc: Expecting ',' delimiter: line 24 column 2 (char 470)
0.0
Error processing NCT NCT00846703_inc: Expecting ',' delimiter: line 105 column 2 (char 3764)
0.0
Error processing NCT NCT02944604_inc: Expecting ',' delimiter: line 55 column 2 (char 1630)
Error processing NCT NCT03004209_exc: Expecting ',' delimiter: line 79 column 2 (char 1997)
Error processing NCT NCT02667730_exc: Extra data: line 38 column 1 (char 1067)
Error processing NCT NCT02321839_inc: Expecting ',' delimiter: line 35 column 2 (char 818)
Error processing NCT NCT00480129_inc: Expecting ',' delimiter: line 13 column 2 (char 411)
Error processing NCT NCT01116882_inc: Expecting ',' delimiter: line 79 column 2 (char 4004)
Error processing NCT NCT02109081_exc: Expecting ',' delimiter: line 8 column 2 (char 426)
Error processing NCT NCT02798237_exc: Extra data: line 22 column 1 (char 677)
Error processing NCT NCT01816997_exc: Expecting ',' delimiter: line 60 column 2 (char 1693)
Error processing NCT NCT01768195_exc: Extra data: line 24 column 1 (char 440)
Error processing NCT NCT01314898_exc: Extra data: line 25 column 1 (char 812)
Error processing NCT NCT02526823_exc: Expecting ',' delimiter: line 45 column 2 (char 1569)
2.272727272727273
Error processing NCT NCT02542956_exc: Extra data: line 24 column 1 (char 524)
Error processing NCT NCT01228279_inc: Expecting ',' delimiter: line 17 column 2 (char 340)
1.5384615384615385
Error processing NCT NCT02316886_inc: Expecting ',' delimiter: line 76 column 2 (char 3163)
11.11111111111111
0.0
0.0
Error processing NCT NCT02053246_exc: Expecting ',' delimiter: line 16 column 17 (char 468)
Error processing NCT NCT02489045_inc: Expecting ',' delimiter: line 51 column 2 (char 1373)
Error processing NCT NCT02827526_exc: Extra data: line 47 column 3 (char 1560)
0.0
Error processing NCT NCT02046395_inc: Expecting ',' delimiter: line 35 column 2 (char 786)
0.0
15.789473684210526
0.0
17.647058823529413
Error processing NCT NCT01735955_inc: Expecting ',' delimiter: line 34 column 2 (char 1203)
0.0
Error processing NCT NCT02894372_inc: Expecting ',' delimiter: line 17 column 2 (char 424)
Error processing NCT NCT02783859_inc: Expecting ',' delimiter: line 36 column 2 (char 1285)
Error processing NCT NCT02822001_exc: Expecting ',' delimiter: line 40 column 2 (char 1037)
Error processing NCT NCT00785213_exc: Expecting ',' delimiter: line 57 column 2 (char 1809)
0.0
Error processing NCT NCT02361905_inc: Expecting ',' delimiter: line 27 column 2 (char 624)
Error processing NCT NCT00730301_exc: Extra data: line 122 column 5 (char 4213)
5.0
Error processing NCT NCT01680081_exc: Expecting ',' delimiter: line 37 column 2 (char 1319)
Error processing NCT NCT02281643_exc: Expecting ',' delimiter: line 37 column 2 (char 918)
Error processing NCT NCT03015818_exc: Expecting ',' delimiter: line 38 column 2 (char 944)
12.5
Error processing NCT NCT02083991_inc: Expecting ',' delimiter: line 20 column 2 (char 490)
14.117647058823529
0.0
Error processing NCT NCT01959425_inc: Expecting ',' delimiter: line 68 column 2 (char 2139)
Error processing NCT NCT01349413_inc: Extra data: line 24 column 1 (char 510)
14.285714285714285
Error processing NCT NCT02974660_exc: Expecting ',' delimiter: line 24 column 2 (char 643)
Error processing NCT NCT02982577_exc: Expecting ',' delimiter: line 16 column 2 (char 498)
Error processing NCT NCT02560389_exc: Expecting ',' delimiter: line 63 column 2 (char 1950)
Error processing NCT NCT02600000_exc: Expecting ',' delimiter: line 55 column 2 (char 1575)
Error processing NCT NCT02564471_exc: Expecting ',' delimiter: line 66 column 2 (char 2832)
Error processing NCT NCT02868437_inc: Expecting ',' delimiter: line 6 column 2 (char 129)
0.0
2.857142857142857
Error processing NCT NCT00943865_exc: Expecting ',' delimiter: line 70 column 2 (char 2640)
0.0
Error processing NCT NCT02150590_inc: Expecting ',' delimiter: line 23 column 2 (char 416)
0.0
Error processing NCT NCT02371200_inc: Expecting ',' delimiter: line 63 column 2 (char 2216)
12.068965517241379
Error processing NCT NCT00989261_inc: Expecting ',' delimiter: line 147 column 2 (char 4139)
7.8125
Error processing NCT NCT02678663_exc: Expecting ',' delimiter: line 24 column 2 (char 606)
Error processing NCT NCT01352598_inc: Extra data: line 91 column 3 (char 2543)
Error processing NCT NCT02432404_exc: Expecting ',' delimiter: line 44 column 2 (char 1359)
0.0
Error processing NCT NCT02589977_inc: Expecting ',' delimiter: line 42 column 2 (char 1491)
Error processing NCT NCT02431442_inc: Expecting ',' delimiter: line 86 column 2 (char 4407)
Error processing NCT NCT02680054_exc: Expecting ',' delimiter: line 44 column 2 (char 1388)
Error processing NCT NCT02003339_exc: Extra data: line 66 column 1 (char 3071)
Error processing NCT NCT02872935_inc: Expecting ',' delimiter: line 38 column 2 (char 913)
Error processing NCT NCT02390973_inc: Extra data: line 31 column 1 (char 653)
Error processing NCT NCT02035904_exc: Expecting ',' delimiter: line 16 column 2 (char 708)
Error processing NCT NCT02437045_inc: Expecting ',' delimiter: line 41 column 2 (char 1384)
Error processing NCT NCT02406885_exc: Expecting ',' delimiter: line 94 column 2 (char 2582)
Error processing NCT NCT02426034_inc: Extra data: line 99 column 25 (char 5946)
Error processing NCT NCT03013790_exc: Extra data: line 54 column 5 (char 1909)
Error processing NCT NCT02560766_exc: Expecting ',' delimiter: line 75 column 2 (char 3881)
Error processing NCT NCT01943812_exc: Expecting ',' delimiter: line 32 column 2 (char 642)
6.0606060606060606
Error processing NCT NCT02416869_exc: Expecting ',' delimiter: line 17 column 2 (char 282)
Error processing NCT NCT02782702_inc: Expecting ',' delimiter: line 49 column 2 (char 1310)
0.0
Error processing NCT NCT02858180_inc: Expecting ',' delimiter: line 88 column 2 (char 3731)
Error processing NCT NCT02886962_exc: Extra data: line 56 column 9 (char 2187)
5.714285714285714
Error processing NCT NCT02884401_inc: Expecting ',' delimiter: line 62 column 2 (char 2949)
Error processing NCT NCT02579928_exc: Expecting ',' delimiter: line 36 column 2 (char 1209)
Error processing NCT NCT00461136_exc: Expecting ',' delimiter: line 79 column 69 (char 4818)
Error processing NCT NCT02946892_inc: Expecting ',' delimiter: line 24 column 2 (char 712)
Error processing NCT NCT02254668_inc: Expecting ',' delimiter: line 24 column 2 (char 428)
Error processing NCT NCT02537899_exc: Expecting ',' delimiter: line 28 column 2 (char 798)
Error processing NCT NCT01567605_exc: Expecting ',' delimiter: line 70 column 2 (char 2525)
23.52941176470588
0.0
Error processing NCT NCT01942109_exc: Expecting ',' delimiter: line 45 column 2 (char 1149)
Error processing NCT NCT00319748_inc: Extra data: line 136 column 1 (char 5207)
Error processing NCT NCT01768195_inc: Expecting ',' delimiter: line 31 column 2 (char 710)
Error processing NCT NCT00625742_inc: Expecting ',' delimiter: line 54 column 2 (char 1968)
Error processing NCT NCT00749112_exc: Expecting ',' delimiter: line 13 column 2 (char 235)
0.0
Error processing NCT NCT01715584_exc: Expecting ',' delimiter: line 45 column 2 (char 1219)
Error processing NCT NCT02990403_exc: Extra data: line 52 column 1 (char 1767)
0.0
Error processing NCT NCT02957305_exc: Expecting ',' delimiter: line 91 column 2 (char 2803)
0.0
10.0
Error processing NCT NCT02121145_exc: Expecting ',' delimiter: line 26 column 25 (char 1262)
0.0
Error processing NCT NCT02478515_exc: Expecting ',' delimiter: line 37 column 2 (char 952)
Error processing NCT NCT02609425_inc: Expecting ',' delimiter: line 13 column 2 (char 342)
23.076923076923077
Error processing NCT NCT02678962_exc: Expecting ',' delimiter: line 52 column 2 (char 1890)
14.925373134328357
13.333333333333334
0.0
29.166666666666668
0.0
13.636363636363635
Error processing NCT NCT02502734_inc: Expecting ',' delimiter: line 72 column 2 (char 4728)
Error processing NCT NCT02231892_exc: Expecting ',' delimiter: line 79 column 2 (char 6010)
0.0
Error processing NCT NCT02773173_exc: Extra data: line 52 column 1 (char 1594)
0.0
Error processing NCT NCT02464865_exc: Expecting ',' delimiter: line 45 column 2 (char 1259)
Error processing NCT NCT02566863_exc: Expecting ',' delimiter: line 24 column 2 (char 504)
14.814814814814813
Error processing NCT NCT02205931_exc: Expecting ',' delimiter: line 88 column 2 (char 2681)
Error processing NCT NCT02944292_inc: Expecting ',' delimiter: line 42 column 2 (char 1190)
Error processing NCT NCT02968602_exc: Expecting ':' delimiter: line 70 column 112 (char 4201)
Error processing NCT NCT02596555_exc: Extra data: line 66 column 1 (char 3937)
Error processing NCT NCT02301039_exc: Expecting ',' delimiter: line 110 column 2 (char 5617)
5.555555555555555
Error processing NCT NCT02552459_exc: Expecting ',' delimiter: line 31 column 2 (char 808)
Error processing NCT NCT01943409_inc: Expecting ',' delimiter: line 24 column 2 (char 599)
Error processing NCT NCT02858180_exc: Expecting ',' delimiter: line 149 column 2 (char 4138)
8.108108108108109
Error processing NCT NCT02630628_exc: Expecting ':' delimiter: line 46 column 41 (char 2488)
0.0
Error processing NCT NCT02686021_exc: Expecting ',' delimiter: line 43 column 2 (char 1570)
0.0
25.0
Error processing NCT NCT02334631_exc: Expecting ',' delimiter: line 31 column 2 (char 927)
Error processing NCT NCT02632760_inc: Expecting ',' delimiter: line 24 column 2 (char 548)
Error processing NCT NCT02323399_inc: Expecting ',' delimiter: line 45 column 2 (char 1573)
Error processing NCT NCT02871206_exc: Expecting ',' delimiter: line 39 column 2 (char 1044)
0.0
Error processing NCT NCT00894712_exc: Expecting ',' delimiter: line 41 column 2 (char 970)
0.0
Error processing NCT NCT02375295_inc: Expecting ',' delimiter: line 45 column 2 (char 1125)
Error processing NCT NCT02595190_exc: Expecting ',' delimiter: line 44 column 2 (char 1460)
Error processing NCT NCT02369211_inc: Expecting ',' delimiter: line 22 column 2 (char 425)
0.0
Error processing NCT NCT00324363_inc: Expecting ',' delimiter: line 24 column 2 (char 703)
Error processing NCT NCT02553226_inc: Expecting ',' delimiter: line 6 column 2 (char 171)
0.0
Error processing NCT NCT02780427_inc: Expecting ',' delimiter: line 24 column 2 (char 553)
Error processing NCT NCT02862912_exc: Expecting ',' delimiter: line 31 column 2 (char 863)
Error processing NCT NCT01803828_exc: Expecting ',' delimiter: line 39 column 2 (char 922)
Error processing NCT NCT02650024_exc: Expecting ',' delimiter: line 130 column 2 (char 5855)
Error processing NCT NCT02541955_inc: Expecting ',' delimiter: line 41 column 2 (char 1052)
0.0
0.0
Error processing NCT NCT02735902_exc: Expecting ',' delimiter: line 63 column 2 (char 2250)
0.0
Error processing NCT NCT02961582_exc: Expecting ',' delimiter: line 68 column 2 (char 2596)
Error processing NCT NCT02365870_inc: Expecting ',' delimiter: line 24 column 2 (char 471)
0.0
0.0
Error processing NCT NCT02924090_inc: Expecting ',' delimiter: line 27 column 2 (char 569)
0.0
Error processing NCT NCT02664558_inc: Expecting ',' delimiter: line 70 column 2 (char 3243)
Error processing NCT NCT02316886_exc: Extra data: line 70 column 9 (char 2858)
Error processing NCT NCT01579604_exc: Expecting ',' delimiter: line 47 column 2 (char 1446)
Error processing NCT NCT02042287_inc: Expecting ',' delimiter: line 58 column 2 (char 1724)
4.545454545454546
Error processing NCT NCT02283996_exc: Expecting ',' delimiter: line 24 column 2 (char 586)
Error processing NCT NCT02384850_inc: Expecting ',' delimiter: line 65 column 2 (char 2784)
Error processing NCT NCT01401335_inc: Expecting ',' delimiter: line 6 column 2 (char 187)
0.0
Error processing NCT NCT02897856_exc: Expecting ',' delimiter: line 63 column 2 (char 2038)
Error processing NCT NCT00806273_exc: Expecting ',' delimiter: line 35 column 2 (char 848)
6.329113924050633
0.0
Error processing NCT NCT02385045_exc: Expecting ',' delimiter: line 70 column 2 (char 2948)
Error processing NCT NCT01175044_exc: Expecting ',' delimiter: line 30 column 15 (char 857)
16.129032258064516
Error processing NCT NCT02748330_inc: Expecting ',' delimiter: line 92 column 2 (char 3787)
Error processing NCT NCT02647788_exc: Expecting ',' delimiter: line 9 column 2 (char 464)
0.0
Error processing NCT NCT01261832_inc: Expecting ',' delimiter: line 6 column 2 (char 135)
0.0
Error processing NCT NCT02687178_inc: Expecting ',' delimiter: line 6 column 2 (char 226)
Error processing NCT NCT00639795_exc: Extra data: line 76 column 10 (char 3371)
Error processing NCT NCT01891383_inc: Expecting ',' delimiter: line 101 column 2 (char 4143)
Error processing NCT NCT00425789_inc: Expecting ',' delimiter: line 35 column 2 (char 1122)
5.660377358490567
Error processing NCT NCT01911650_exc: Expecting ',' delimiter: line 65 column 2 (char 2289)
13.333333333333334

In [10]:
df_success = pd.DataFrame(success_data).set_index('NCT')
df_success.to_csv(eval_path+f'/{model}_eval.csv')

df_success

,label_AND,label_OR,label_NOT,label_DEPTH,model_AND,model_OR,model_NOT,model_DEPTH,diff_AND,diff_OR,diff_NOT,diff_DEPTH
NCT,,,,,,,,,,,,
NCT02966236_inc,2,0,0,5,1,0,0,3,-1,0,0,-1
NCT02566226_exc,6,0,0,11,1,4,0,11,-1,1,0,0
NCT02933671_inc,3,0,0,7,3,1,0,8,0,1,0,1
NCT02816164_inc,4,6,0,17,5,1,0,13,1,-1,0,-1
NCT01944800_exc,1,0,0,3,1,1,0,5,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
NCT01631058_exc,3,2,0,9,1,2,0,7,-1,0,0,-1
NCT02200978_exc,1,3,0,9,1,1,0,5,0,-1,0,-1
NCT02469610_exc,1,0,0,3,1,0,0,3,0,0,0,0
NCT02859480_inc,2,0,0,5,1,0,0,3,-1,0,0,-1
NCT01491295_exc,3,5,0,9,2,1,0,5,-1,-1,0,-1

In [11]:
true_values = df_success[['label_AND', 'label_OR', 'label_NOT', 'label_DEPTH']].values
predicted_values = df_success[['model_AND', 'model_OR', 'model_NOT', 'model_DEPTH']].values

metrics = {}
for i, metric in enumerate(['AND', 'OR', 'NOT', 'DEPTH']):
    y_true = true_values[:, i]
    y_pred = predicted_values[:, i]

    diffs = y_pred - y_true
    pct_greater = (diffs > 0).sum() / len(diffs) * 100
    pct_less = (diffs < 0).sum() / len(diffs) * 100
    pct_equal = (diffs == 0).sum() / len(diffs) * 100


    metrics[metric] = {
        'accuracy': round(accuracy_score(y_true, y_pred), 3),
        'precision': round(precision_score(y_true, y_pred, average='weighted', zero_division=0), 3),
        'recall': round(recall_score(y_true, y_pred, average='weighted', zero_division=0), 3),
        'f1_score': round(f1_score(y_true, y_pred, average='weighted', zero_division=0), 3),
        'pct_greater': round(pct_greater, 2),
        'pct_less': round(pct_less, 2),
        'pct_equal': round(pct_equal, 2)
       # 'confusion_matrix': confusion_matrix(y_true, y_pred)
    }
    metrics_df = pd.DataFrame(metrics).T  
    num_nct_files = len(df_success)
    metrics_df['num_nct_files'] = num_nct_files
    metrics_df['model_name'] = model
    # Save Metrics to CSV
    metrics_df.to_csv(os.path.join(eval_path, f'{model}_metrics_summary.csv'))

print(f"{len(df_success)} Daten mit {model}")
for metric, values in metrics.items():
    print(f"Metrics for {metric}:")
    print(f"  Accuracy: {values['accuracy']}")
    print(f"  Precision: {values['precision']}")
    print(f"  Recall: {values['recall']}")
    print(f"  F1 Score: {values['f1_score']}")

    print(f"  % Greater: {values['pct_greater']}")
    print(f"  % Less: {values['pct_less']}")
    print(f"  % Equal: {values['pct_equal']}")
    print()
    #print(f"  Confusion Matrix:\n{values['confusion_matrix']}\n")

1032 Daten mit Llama-3-8B-Instruct-Gradient-1048k_10_shot
Metrics for AND:
  Accuracy: 0.254
  Precision: 0.211
  Recall: 0.254
  F1 Score: 0.188
  % Greater: 6.78
  % Less: 67.83
  % Equal: 25.39

Metrics for OR:
  Accuracy: 0.304
  Precision: 0.416
  Recall: 0.304
  F1 Score: 0.342
  % Greater: 48.06
  % Less: 21.51
  % Equal: 30.43

Metrics for NOT:
  Accuracy: 0.859
  Precision: 0.737
  Recall: 0.859
  F1 Score: 0.793
  % Greater: 0.0
  % Less: 14.15
  % Equal: 85.85

Metrics for DEPTH:
  Accuracy: 0.277
  Precision: 0.315
  Recall: 0.277
  F1 Score: 0.284
  % Greater: 32.56
  % Less: 39.73
  % Equal: 27.71

In [12]:
matching_rows = df_success[df_success['label_AND'] == df_success['model_AND']][['label_AND', 'model_AND']]
matching_rows

                 label_AND  model_AND
NCT
NCT02933671_inc          3          3
NCT01944800_exc          1          1
NCT02566863_inc          2          2
NCT02456532_inc          1          1
NCT01236417_inc          4          4
...                    ...        ...
NCT02323399_exc          1          1
NCT03012984_inc          5          5
NCT01184638_inc          2          2
NCT02200978_exc          1          1
NCT02469610_exc          1          1

[262 rows x 2 columns]