In [45]:
import json
import os
import pandas as pd
import re
import shutil
from collections import defaultdict
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from functions import *
from eval_functions import *

In [46]:
main_directory = 'model_output'
models = find_folders_with_output(main_directory)

save = True

eval_path = f"evaluate/batch1"
os.makedirs(eval_path, exist_ok=True)

### Model Output to nice JSON and Failure

In [47]:
def process_files(model, save=save):
    input_dir = f"model_output/{model}/output/"
    output_dir = f"model_output/{model}/formatted/"
    failure_dir = f"model_output/{model}/failed/"
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(failure_dir, exist_ok=True)
    files = os.listdir(input_dir)
    len_files = len(files)
    for filename in files:
        if filename.endswith('.json'):
            input_file_path = os.path.join(input_dir, filename)
            output_file_path = os.path.join(output_dir, filename)
            failure_file_path = os.path.join(failure_dir, filename)
            try:
                file = read_json(input_file_path)
                print(f"Processing file: {filename}")
                if save:
                    shutil.copy(input_file_path, output_file_path)
                    #save_json_to_file(file, output_file_path)
            except Exception as e:
                print(f"Error processing file {filename}: {e}")
                if save:
                    shutil.copy(input_file_path, failure_file_path)
    return len_files

In [48]:
num_out_files

300

In [49]:
for model in models:
    print(model)
    # 1 - Preprocess Files
    num_out_files = process_files(model, save=save)
    print(num_out_files)
    # 2 - Evaluate Files
    p2_label_path = "chia_label/p2"
    ready_path = f"model_output/{model}/ready"
    failed_model_path = f"model_output/{model}/failed_inner"
    p2_model_formatted_path = f"model_output/{model}/formatted"
    
    for path in [ready_path, failed_model_path, p2_model_formatted_path]:
        os.makedirs(path, exist_ok=True)
    
    label_files = {extract_nct_number(f): os.path.join(p2_label_path, f) for f in os.listdir(p2_label_path) if f.endswith('.json')}
    model_files = {extract_nct_number(f): os.path.join(p2_model_formatted_path, f) for f in os.listdir(p2_model_formatted_path) if f.endswith('.json')}
    
    common_ncts = set(label_files.keys()).intersection(model_files.keys())
    labels = []
    predictions = []
    success_data = []
    
    for nct in common_ncts:
        try:
            label_data = read_json(label_files[nct])
            model_data = read_json(model_files[nct])
            print(model_data)
            label_structure = extract_logical_structure(label_data)
            model_structure = extract_logical_structure(model_data)
    
            # Try count words
            label_raw_texts = extract_raw_texts(label_data)
            model_raw_texts = extract_raw_texts(model_data)
            
            missing_texts = label_raw_texts - model_raw_texts
            
            label_words = extract_words(label_raw_texts)
            model_words = extract_words(model_raw_texts)
            missing_words = label_words - model_words
            missing_words_pct = len(missing_words) / len(label_words) * 100 if label_words else 0
            print(f"Processing NCT {nct}")
            print(round(missing_words_pct,2), "%")
            print(label_words.issubset(model_words))
            print("Label Text \n")
            print(label_words)
            print("\nModel Text \n")
            print(model_words)
            print()
            
            success_data.append({
                'NCT': nct,
                'label_AND': label_structure.get('AND', 0),
                'label_OR': label_structure.get('OR', 0),
                'label_NOT': label_structure.get('NOT', 0),
                'label_DEPTH': label_structure.get('depth', 0),
                'model_AND': model_structure.get('AND', 0),
                'model_OR': model_structure.get('OR', 0),
                'model_NOT': model_structure.get('NOT', 0),
                'model_DEPTH': model_structure.get('depth', 0),
                'diff_AND': 1 if model_structure.get('AND', 0) > label_structure.get('AND', 0) else -1 if model_structure.get('AND', 0) < label_structure.get('AND', 0) else 0,
                'diff_OR': 1 if model_structure.get('OR', 0) > label_structure.get('OR', 0) else -1 if model_structure.get('OR', 0) < label_structure.get('OR', 0) else 0,
                'diff_NOT': 1 if model_structure.get('NOT', 0) > label_structure.get('NOT', 0) else -1 if model_structure.get('NOT', 0) < label_structure.get('NOT', 0) else 0,
                'diff_DEPTH': 1 if model_structure.get('depth', 0) > label_structure.get('depth', 0) else -1 if model_structure.get('depth', 0) < label_structure.get('depth', 0) else 0,
                'num_out_files': num_out_files,
            })
    
            labels.append(label_structure)
            predictions.append(model_structure)
            save and shutil.copy(model_files[nct], os.path.join(ready_path, os.path.basename(model_files[nct])))
        except Exception as e:
            #print(f"Error processing NCT {nct}: {e}")
            save and shutil.copy(model_files[nct], os.path.join(failed_model_path, os.path.basename(model_files[nct])))
    
    df_success = pd.DataFrame(success_data).set_index('NCT')
    df_success.to_csv(eval_path+f'/{model}_eval.csv')
    true_values = df_success[['label_AND', 'label_OR', 'label_NOT', 'label_DEPTH']].values
    predicted_values = df_success[['model_AND', 'model_OR', 'model_NOT', 'model_DEPTH']].values
    
    metrics = {}
    for i, metric in enumerate(['AND', 'OR', 'NOT', 'DEPTH']):
        y_true = true_values[:, i]
        y_pred = predicted_values[:, i]
    
        diffs = y_pred - y_true
        pct_greater = (diffs > 0).sum() / len(diffs) * 100
        pct_less = (diffs < 0).sum() / len(diffs) * 100
        pct_equal = (diffs == 0).sum() / len(diffs) * 100
    
        metrics[metric] = {
            'accuracy': round(accuracy_score(y_true, y_pred), 3),
            'precision': round(precision_score(y_true, y_pred, average='weighted', zero_division=0), 3),
            'recall': round(recall_score(y_true, y_pred, average='weighted', zero_division=0), 3),
            'f1_score': round(f1_score(y_true, y_pred, average='weighted', zero_division=0), 3),
            'pct_greater': round(pct_greater, 2),
            'pct_less': round(pct_less, 2),
            'pct_equal': round(pct_equal, 2)
            # 'confusion_matrix': confusion_matrix(y_true, y_pred)
        }
        metrics_df = pd.DataFrame(metrics).T
        num_nct_files = len(df_success)
        metrics_df['num_nct_files'] = num_nct_files
        metrics_df['model_name'] = model
        metrics_df['num_files'] = anzahl_files
        # Save Metrics to CSV
        metrics_df.to_csv(os.path.join(eval_path, f'{model}_metrics_summary.csv'))

Llama-3-8B-Instruct_4_shot
Processing file: Llama-3-8B-Instruct_NCT00050349_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00050349_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00061308_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00061308_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00094861_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00094861_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00122070_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00122070_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00182520_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00182520_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00183885_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00183885_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00198913_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00198913_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00235170_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00235170_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00236340_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00236340_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00250640_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00250640_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00279552_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00279552_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00305097_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00305097_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00312429_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00312429_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00317148_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00317148_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00319748_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00319748_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00324363_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00324363_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00343668_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00343668_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00344318_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00344318_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00351611_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00351611_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00356148_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00356148_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00379366_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00379366_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00391690_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00391690_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00396734_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00396734_inc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT00397215_exc_4_shot.json: Extra data: line 190 column 1 (char 8454)
Processing file: Llama-3-8B-Instruct_NCT00397215_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00401245_exc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT00401245_inc_4_shot.json: Expecting ',' delimiter: line 92 column 2 (char 2200)
Processing file: Llama-3-8B-Instruct_NCT00404495_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00404495_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00425789_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00425789_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00426751_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00426751_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00440245_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00440245_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00445029_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00445029_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00455663_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00455663_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00461136_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00461136_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00480129_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00480129_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00483106_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00483106_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00500500_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00500500_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00502567_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00502567_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00527826_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00527826_inc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT00543712_exc_4_shot.json: Expecting ',' delimiter: line 240 column 4 (char 5669)
Processing file: Llama-3-8B-Instruct_NCT00543712_inc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT00576173_exc_4_shot.json: Extra data: line 48 column 1 (char 1159)
Processing file: Llama-3-8B-Instruct_NCT00576173_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00586898_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00586898_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00599924_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00599924_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00609531_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00609531_inc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT00625742_exc_4_shot.json: Extra data: line 23 column 1 (char 369)
Processing file: Llama-3-8B-Instruct_NCT00625742_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00639795_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00639795_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00650312_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00650312_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00676273_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00676273_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00679341_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00679341_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00718952_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00718952_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00720031_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00720031_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00728156_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00728156_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00730301_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00730301_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00749112_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00749112_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00752310_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00752310_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00785213_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00785213_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00787254_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00787254_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00806273_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00806273_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00806936_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00806936_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00812344_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00812344_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00846703_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00846703_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00862446_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00862446_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00867958_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00867958_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00886158_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00886158_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00894712_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00894712_inc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT00904202_exc_4_shot.json: Extra data: line 18 column 1 (char 581)
Processing file: Llama-3-8B-Instruct_NCT00904202_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00917891_exc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT00917891_inc_4_shot.json: Extra data: line 156 column 149 (char 18472)
Processing file: Llama-3-8B-Instruct_NCT00926523_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00926523_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00931983_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00931983_inc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT00943865_exc_4_shot.json: Extra data: line 23 column 1 (char 355)
Processing file: Llama-3-8B-Instruct_NCT00943865_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00954850_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00954850_inc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT00959569_exc_4_shot.json: Expecting ',' delimiter: line 22 column 4 (char 384)
Processing file: Llama-3-8B-Instruct_NCT00959569_inc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT00962364_exc_4_shot.json: Extra data: line 3 column 1 (char 4)
Error processing file Llama-3-8B-Instruct_NCT00962364_inc_4_shot.json: Extra data: line 24 column 2 (char 448)
Processing file: Llama-3-8B-Instruct_NCT00965900_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00965900_inc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT00970866_exc_4_shot.json: Expecting property name enclosed in double quotes: line 13 column 12 (char 245)
Processing file: Llama-3-8B-Instruct_NCT00970866_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00989261_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00989261_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00994786_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT00994786_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01000155_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01000155_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01009359_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01009359_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01032109_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01032109_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01051414_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01051414_inc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT01064752_exc_4_shot.json: Extra data: line 40 column 1 (char 846)
Processing file: Llama-3-8B-Instruct_NCT01064752_inc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT01078051_exc_4_shot.json: Expecting value: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT01078051_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01082549_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01082549_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01084993_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01084993_inc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT01088750_exc_4_shot.json: Expecting value: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT01088750_inc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT01098383_exc_4_shot.json: Extra data: line 103 column 17 (char 4230)
Processing file: Llama-3-8B-Instruct_NCT01098383_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01116882_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01116882_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01116973_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01116973_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01117181_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01117181_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01118871_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01118871_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01175044_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01175044_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01177891_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01177891_inc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT01184638_exc_4_shot.json: Expecting property name enclosed in double quotes: line 18 column 8 (char 365)
Processing file: Llama-3-8B-Instruct_NCT01184638_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01205334_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01205334_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01214096_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01214096_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01217671_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01217671_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01218737_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01218737_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01228279_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01228279_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01236417_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01236417_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01261832_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01261832_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01312012_exc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT01312012_inc_4_shot.json: Expecting ',' delimiter: line 37 column 2 (char 814)
Error processing file Llama-3-8B-Instruct_NCT01313676_exc_4_shot.json: Expecting value: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT01313676_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01314898_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01314898_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01320579_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01320579_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01322464_exc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT01322464_inc_4_shot.json: Extra data: line 166 column 6 (char 5780)
Processing file: Llama-3-8B-Instruct_NCT01346436_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01346436_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01349413_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01349413_inc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT01352598_exc_4_shot.json: Expecting value: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT01352598_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01373684_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01373684_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01391780_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01391780_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01401335_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01401335_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01410890_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01410890_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01424020_exc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT01424020_inc_4_shot.json: Expecting ',' delimiter: line 22 column 4 (char 323)
Processing file: Llama-3-8B-Instruct_NCT01440296_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01440296_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01446094_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01446094_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01483118_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01483118_inc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT01490034_exc_4_shot.json: Expecting value: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT01490034_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01491295_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01491295_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01491763_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01491763_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01497639_exc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT01497639_inc_4_shot.json: Extra data: line 46 column 1 (char 1036)
Processing file: Llama-3-8B-Instruct_NCT01501201_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01501201_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01518946_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01518946_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01531257_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01531257_inc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT01567605_exc_4_shot.json: Extra data: line 21 column 2 (char 394)
Processing file: Llama-3-8B-Instruct_NCT01567605_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01579604_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01579604_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01581749_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01581749_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01602081_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01602081_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01604187_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01604187_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01614041_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01614041_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01630954_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01630954_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01631058_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01631058_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01639664_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01639664_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01642875_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01642875_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01650792_exc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT01650792_inc_4_shot.json: Extra data: line 18 column 1 (char 317)
Processing file: Llama-3-8B-Instruct_NCT01664507_exc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT01664507_inc_4_shot.json: Expecting ',' delimiter: line 38 column 18 (char 780)
Processing file: Llama-3-8B-Instruct_NCT01665417_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01665417_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01669369_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01669369_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01680081_exc_4_shot.json
Error processing file Llama-3-8B-Instruct_NCT01680081_inc_4_shot.json: Expecting ',' delimiter: line 30 column 1 (char 753)
Processing file: Llama-3-8B-Instruct_NCT01684501_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01684501_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01696617_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01696617_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01700790_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01700790_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01701219_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01701219_inc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01709981_exc_4_shot.json
Processing file: Llama-3-8B-Instruct_NCT01709981_inc_4_shot.json

In [50]:
# NCT02935855_inc

In [51]:
df_success = pd.DataFrame(success_data).set_index('NCT')
df_success.to_csv(eval_path+f'/{model}_eval.csv')

df_success

,label_AND,label_OR,label_NOT,label_DEPTH,model_AND,model_OR,model_NOT,model_DEPTH,diff_AND,diff_OR,diff_NOT,diff_DEPTH,num_out_files
NCT,,,,,,,,,,,,,
NCT01728194_inc,6,1,0,11,7,0,0,11,1,-1,0,0,300
NCT00050349_exc,20,18,3,35,1,3,0,7,-1,-1,-1,-1,300
NCT01084993_exc,2,3,1,13,1,3,0,7,-1,0,-1,-1,300
NCT01000155_exc,14,8,3,29,1,1,0,5,-1,-1,-1,-1,300
NCT00182520_inc,4,11,0,23,2,0,0,5,-1,-1,0,-1,300
...,...,...,...,...,...,...,...,...,...,...,...,...,...
NCT01175044_inc,0,0,0,1,0,0,0,1,0,0,0,0,300
NCT00440245_inc,0,1,0,3,0,1,0,3,0,0,0,0,300
NCT00397215_inc,3,2,0,9,6,1,0,7,1,-1,0,-1,300
NCT01483118_inc,4,3,0,9,10,0,0,11,1,-1,0,1,300
NCT01373684_exc,18,21,2,35,2,7,0,15,-1,-1,-1,-1,300

In [52]:
true_values = df_success[['label_AND', 'label_OR', 'label_NOT', 'label_DEPTH']].values
predicted_values = df_success[['model_AND', 'model_OR', 'model_NOT', 'model_DEPTH']].values

metrics = {}
for i, metric in enumerate(['AND', 'OR', 'NOT', 'DEPTH']):
    y_true = true_values[:, i]
    y_pred = predicted_values[:, i]

    diffs = y_pred - y_true
    pct_greater = (diffs > 0).sum() / len(diffs) * 100
    pct_less = (diffs < 0).sum() / len(diffs) * 100
    pct_equal = (diffs == 0).sum() / len(diffs) * 100


    metrics[metric] = {
        'accuracy': round(accuracy_score(y_true, y_pred), 3),
        'precision': round(precision_score(y_true, y_pred, average='weighted', zero_division=0), 3),
        'recall': round(recall_score(y_true, y_pred, average='weighted', zero_division=0), 3),
        'f1_score': round(f1_score(y_true, y_pred, average='weighted', zero_division=0), 3),
        'pct_greater': round(pct_greater, 2),
        'pct_less': round(pct_less, 2),
        'pct_equal': round(pct_equal, 2)
       # 'confusion_matrix': confusion_matrix(y_true, y_pred)
    }
    metrics_df = pd.DataFrame(metrics).T  
    num_nct_files = len(df_success)
    metrics_df['num_out_files'] = anzahl_files
    metrics_df['num_nct_files'] = num_nct_files
    metrics_df['model_name'] = model
    # Save Metrics to CSV
    metrics_df.to_csv(os.path.join(eval_path, f'{model}_metrics_summary.csv'))

print(f"{len(df_success)} Daten mit {model}")
for metric, values in metrics.items():
    print(f"Metrics for {metric}:")
    print(f"  Accuracy: {values['accuracy']}")
    print(f"  Precision: {values['precision']}")
    print(f"  Recall: {values['recall']}")
    print(f"  F1 Score: {values['f1_score']}")

    print(f"  % Greater: {values['pct_greater']}")
    print(f"  % Less: {values['pct_less']}")
    print(f"  % Equal: {values['pct_equal']}")
    print()
    #print(f"  Confusion Matrix:\n{values['confusion_matrix']}\n")

270 Daten mit Llama-3-8B-Instruct_4_shot
Metrics for AND:
  Accuracy: 0.119
  Precision: 0.104
  Recall: 0.119
  F1 Score: 0.105
  % Greater: 32.22
  % Less: 55.93
  % Equal: 11.85

Metrics for OR:
  Accuracy: 0.274
  Precision: 0.28
  Recall: 0.274
  F1 Score: 0.269
  % Greater: 33.33
  % Less: 39.26
  % Equal: 27.41

Metrics for NOT:
  Accuracy: 0.644
  Precision: 0.544
  Recall: 0.644
  F1 Score: 0.57
  % Greater: 5.19
  % Less: 30.37
  % Equal: 64.44

Metrics for DEPTH:
  Accuracy: 0.159
  Precision: 0.143
  Recall: 0.159
  F1 Score: 0.142
  % Greater: 25.19
  % Less: 58.89
  % Equal: 15.93

In [53]:
metrics_df

,accuracy,precision,recall,f1_score,pct_greater,pct_less,pct_equal,num_out_files,num_nct_files,model_name
AND,0.119,0.104,0.119,0.105,32.22,55.93,11.85,300,270,Llama-3-8B-Instruct_4_shot
OR,0.274,0.280,0.274,0.269,33.33,39.26,27.41,300,270,Llama-3-8B-Instruct_4_shot
NOT,0.644,0.544,0.644,0.570,5.19,30.37,64.44,300,270,Llama-3-8B-Instruct_4_shot
DEPTH,0.159,0.143,0.159,0.142,25.19,58.89,15.93,300,270,Llama-3-8B-Instruct_4_shot

In [54]:
matching_rows = df_success[df_success['label_AND'] == df_success['model_AND']][['label_AND', 'model_AND']]
matching_rows

                 label_AND  model_AND
NCT
NCT00198913_exc          0          0
NCT01501201_inc          3          3
NCT01184638_inc          1          1
NCT01720394_inc         10         10
NCT01581749_exc          4          4
NCT01604187_inc          2          2
NCT00639795_inc          1          1
NCT00886158_exc          0          0
NCT01314898_exc          2          2
NCT00312429_exc          2          2
NCT00351611_inc          2          2
NCT00396734_exc          2          2
NCT00502567_inc          3          3
NCT01312012_exc          5          5
NCT01684501_inc          3          3
NCT00440245_exc          0          0
NCT01604187_exc          7          7
NCT01346436_inc          2          2
NCT00483106_inc          0          0
NCT01032109_exc          4          4
NCT01446094_inc          1          1
NCT00862446_exc          1          1
NCT01373684_inc          7          7
NCT00862446_inc          3          3
NCT01088750_inc          2          2
NCT01051414_inc          1          1
NCT01440296_exc          0          0
NCT01228279_inc          1          1
NCT01602081_inc          0          0
NCT01642875_exc          8          8
NCT01175044_inc          0          0
NCT00440245_inc          0          0