In [36]:
import json
import os
import pandas as pd
import re
import shutil
from collections import defaultdict
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from functions import *

In [37]:
model = "Llama-3-8B-Instruct_5_shot"

### Model Output to nice JSON and Failure

In [38]:
input_dir = f"model_output/{model}/output/"
output_dir = f"model_output/{model}/formatted/"
failure_dir = f"model_output/{model}/failed/"

if not os.path.exists(output_dir):
    os.makedirs(output_dir)
if not os.path.exists(failure_dir):
    os.makedirs(failure_dir)

for filename in os.listdir(input_dir):
    if filename.endswith('.json'):
        input_file_path = os.path.join(input_dir, filename)
        output_file_path = os.path.join(output_dir, filename)
        failure_file_path = os.path.join(failure_dir, filename)
        try:
            file = read_json(input_file_path)
            print(f"Processing file: {filename}")
            save_json_to_file(file, output_file_path)
        except Exception as e:
            print(f"Error processing file {filename}: {e}")
            shutil.move(input_file_path, failure_file_path)

Processing file: Llama-3-8B-Instruct_NCT00050349_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00050349_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00061308_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00061308_inc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT00094861_exc_5_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Error processing file Llama-3-8B-Instruct_NCT00094861_inc_5_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT00122070_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00122070_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00182520_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00182520_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00183885_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00183885_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00198913_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00198913_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00235170_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00235170_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00236340_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00236340_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00250640_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00250640_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00279552_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00279552_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00305097_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00305097_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00312429_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00312429_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00317148_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00317148_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00319748_exc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT00319748_inc_5_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT00324363_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00324363_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00343668_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00343668_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00344318_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00344318_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00351611_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00351611_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00356148_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00356148_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00379366_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00379366_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00391690_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00391690_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00396734_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00396734_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00397215_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00397215_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00401245_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00401245_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00404495_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00404495_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00425789_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00425789_inc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT00426751_exc_5_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT00426751_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00440245_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00440245_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00445029_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00445029_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00455663_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00455663_inc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT00461136_exc_5_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT00461136_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00480129_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00480129_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00483106_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00483106_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00500500_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00500500_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00502567_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00502567_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00527826_exc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT00527826_inc_5_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT00543712_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00543712_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00576173_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00576173_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00586898_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00586898_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00599924_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00599924_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00609531_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00609531_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00625742_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00625742_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00639795_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00639795_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00650312_exc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT00650312_inc_5_shot.json: Expecting value: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT00676273_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00676273_inc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT00679341_exc_5_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT00679341_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00718952_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00718952_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00720031_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00720031_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00728156_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00728156_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00730301_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00730301_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00749112_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00749112_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00752310_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00752310_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00785213_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00785213_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00787254_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00787254_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00806273_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00806273_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00806936_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00806936_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00812344_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00812344_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00846703_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00846703_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00862446_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00862446_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00867958_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00867958_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00886158_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00886158_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00894712_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00894712_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00904202_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00904202_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00917891_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00917891_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00926523_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00926523_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00931983_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00931983_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00943865_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00943865_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00954850_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00954850_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00959569_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00959569_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00962364_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00962364_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00965900_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00965900_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00970866_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT00970866_inc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT00989261_exc_5_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Error processing file Llama-3-8B-Instruct_NCT00989261_inc_5_shot.json: Extra data: line 1 column 8909 (char 8908)
Error processing file Llama-3-8B-Instruct_NCT00994786_exc_5_shot.json: Extra data: line 1 column 8352 (char 8351)
Processing file: Llama-3-8B-Instruct_NCT00994786_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01000155_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01000155_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01009359_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01009359_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01032109_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01032109_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01051414_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01051414_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01064752_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01064752_inc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT01078051_exc_5_shot.json: Expecting value: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT01078051_inc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT01082549_exc_5_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT01082549_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01084993_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01084993_inc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT01088750_exc_5_shot.json: Expecting value: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT01088750_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01098383_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01098383_inc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT01116882_exc_5_shot.json: Expecting value: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT01116882_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01116973_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01116973_inc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT01117181_exc_5_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT01117181_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01118871_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01118871_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01175044_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01175044_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01177891_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01177891_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01184638_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01184638_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01205334_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01205334_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01214096_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01214096_inc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT01217671_exc_5_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT01217671_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01218737_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01218737_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01228279_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01228279_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01236417_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01236417_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01261832_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01261832_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01312012_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01312012_inc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT01313676_exc_5_shot.json: Expecting value: line 1 column 1 (char 0)
Error processing file Llama-3-8B-Instruct_NCT01313676_inc_5_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT01314898_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01314898_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01320579_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01320579_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01322464_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01322464_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01346436_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01346436_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01349413_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01349413_inc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT01352598_exc_5_shot.json: Expecting value: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT01352598_inc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT01373684_exc_5_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT01373684_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01391780_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01391780_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01401335_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01401335_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01410890_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01410890_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01424020_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01424020_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01440296_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01440296_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01446094_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01446094_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01483118_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01483118_inc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT01490034_exc_5_shot.json: Expecting value: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT01490034_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01491295_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01491295_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01491763_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01491763_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01497639_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01497639_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01501201_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01501201_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01518946_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01518946_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01531257_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01531257_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01567605_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01567605_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01579604_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01579604_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01581749_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01581749_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01602081_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01602081_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01604187_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01604187_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01614041_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01614041_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01630954_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01630954_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01631058_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01631058_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01639664_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01639664_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01642875_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01642875_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01650792_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01650792_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01664507_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01664507_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01665417_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01665417_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01669369_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01669369_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01680081_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01680081_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01684501_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01684501_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01696617_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01696617_inc_5_shot.json
Error processing file Llama-3-8B-Instruct_NCT01700790_exc_5_shot.json: Unterminated string starting at: line 1 column 1 (char 0)
Processing file: Llama-3-8B-Instruct_NCT01700790_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01701219_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01701219_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01709981_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01709981_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01711801_exc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01711801_inc_5_shot.json
Processing file: Llama-3-8B-Instruct_NCT01715584_exc_5_shot.json

In [39]:
p2_label_path = "chia_label/p2"
ready_path = f"model_output/{model}/ready"
failed_model_path = f"model_output/{model}/failed_inner"
p2_model_formatted_path = f"model_output/{model}/formatted"
eval_path = f"evaluate/batch1"

for path in [ready_path, failed_model_path, p2_model_formatted_path]: 
    os.makedirs(path, exist_ok=True)

In [40]:
def extract_nct_number(filename):
    parts = filename.split('_')
    nct_number = None
    file_type = None
    for part in parts:
        if part.startswith("NCT"):
            nct_number = part
        if part in ["inc", "exc"]:
            file_type = part
    return nct_number+"_"+file_type


def extract_logical_structure(data):
    structure = defaultdict(int)
    def traverse(node, depth=0):
        nonlocal structure
        structure["depth"] = max(structure["depth"], depth)

        if isinstance(node, dict):
            for key in node:
                if key in ["AND", "OR", "NOT"]:
                    structure[key] += 1
                traverse(node[key], depth + 1)
        elif isinstance(node, list):
            for item in node:
                traverse(item, depth + 1)

    traverse(data)
    return dict(structure)

In [41]:
label_files = {extract_nct_number(f): os.path.join(p2_label_path, f) for f in os.listdir(p2_label_path) if f.endswith('.json')}
model_files = {extract_nct_number(f): os.path.join(p2_model_formatted_path, f) for f in os.listdir(p2_model_formatted_path) if f.endswith('.json')}

common_ncts = set(label_files.keys()).intersection(model_files.keys())

In [42]:
labels = []
predictions = []
success_data = []

In [43]:
for nct in common_ncts:# ["NCT00050349_exc"]
    try:
        label_data = read_json(label_files[nct])
        model_data = read_json(model_files[nct])
        label_structure = extract_logical_structure(label_data)
        model_structure = extract_logical_structure(model_data)
        success_data.append({
            'NCT': nct,
            'label_AND': label_structure.get('AND', 0),
            'label_OR': label_structure.get('OR', 0),
            'label_NOT': label_structure.get('NOT', 0),
            'label_DEPTH': label_structure.get('depth', 0),
            'model_AND': model_structure.get('AND', 0),
            'model_OR': model_structure.get('OR', 0),
            'model_NOT': model_structure.get('NOT', 0),
            'model_DEPTH': model_structure.get('depth', 0),
            'diff_AND': 1 if model_structure.get('AND', 0) > label_structure.get('AND', 0) else -1 if model_structure.get('AND', 0) < label_structure.get('AND', 0) else 0,
            'diff_OR': 1 if model_structure.get('OR', 0) > label_structure.get('OR', 0) else -1 if model_structure.get('OR', 0) < label_structure.get('OR', 0) else 0,
            'diff_NOT': 1 if model_structure.get('NOT', 0) > label_structure.get('NOT', 0) else -1 if model_structure.get('NOT', 0) < label_structure.get('NOT', 0) else 0,
            'diff_DEPTH': 1 if model_structure.get('depth', 0) > label_structure.get('depth', 0) else -1 if model_structure.get('depth', 0) < label_structure.get('depth', 0) else 0
            
        })

        labels.append(label_structure)
        predictions.append(model_structure)
        shutil.copy(model_files[nct], os.path.join(ready_path, os.path.basename(model_files[nct])))
    except Exception as e:
        print(f"Error processing NCT {nct}: {e}")
        shutil.copy(model_files[nct], os.path.join(failed_model_path, os.path.basename(model_files[nct])))

Error processing NCT NCT01857167_exc: Extra data: line 58 column 5 (char 1533)
Error processing NCT NCT01214096_exc: Expecting ',' delimiter: line 69 column 2 (char 1904)
Error processing NCT NCT02557412_exc: Extra data: line 32 column 1 (char 783)
Error processing NCT NCT02053246_inc: Extra data: line 47 column 1 (char 1125)
Error processing NCT NCT02431442_inc: Expecting ',' delimiter: line 64 column 2 (char 2264)
Error processing NCT NCT02393287_inc: Extra data: line 53 column 1 (char 1230)
Error processing NCT NCT01082549_inc: Expecting ',' delimiter: line 33 column 13 (char 1215)
Error processing NCT NCT02195024_inc: Expecting ',' delimiter: line 80 column 2 (char 2427)
Error processing NCT NCT01803828_inc: Invalid control character at: line 11 column 29 (char 211)
Error processing NCT NCT01483118_inc: Expecting ',' delimiter: line 37 column 101 (char 1399)
Error processing NCT NCT00061308_exc: Extra data: line 37 column 4 (char 661)
Error processing NCT NCT00183885_exc: Expecting ',' delimiter: line 95 column 2 (char 2874)
Error processing NCT NCT02550028_inc: Extra data: line 41 column 1 (char 700)
Error processing NCT NCT00235170_exc: Expecting ',' delimiter: line 80 column 2 (char 2467)
Error processing NCT NCT02196285_inc: Expecting ',' delimiter: line 80 column 2 (char 3143)
Error processing NCT NCT01604187_exc: Expecting ',' delimiter: line 104 column 2 (char 3062)
Error processing NCT NCT01997112_exc: Extra data: line 59 column 2 (char 1353)
Error processing NCT NCT02510404_inc: Extra data: line 56 column 1 (char 1650)
Error processing NCT NCT02339974_inc: Expecting ',' delimiter: line 19 column 70 (char 705)
Error processing NCT NCT02573168_exc: Expecting ',' delimiter: line 87 column 2 (char 2954)
Error processing NCT NCT02322203_exc: Expecting ',' delimiter: line 87 column 2 (char 2197)
Error processing NCT NCT01978028_inc: Extra data: line 74 column 1 (char 2065)
Error processing NCT NCT00720031_inc: Expecting ',' delimiter: line 89 column 2 (char 2926)
Error processing NCT NCT00050349_inc: Expecting ',' delimiter: line 77 column 2 (char 2870)
Error processing NCT NCT00730301_exc: Expecting ',' delimiter: line 90 column 2 (char 2763)
Error processing NCT NCT01846507_exc: Expecting ',' delimiter: line 77 column 2 (char 2473)
Error processing NCT NCT02035904_exc: Extra data: line 40 column 1 (char 718)
Error processing NCT NCT02399033_inc: Expecting ',' delimiter: line 80 column 2 (char 2508)
Error processing NCT NCT02344888_inc: Extra data: line 36 column 1 (char 796)
Error processing NCT NCT02584140_inc: Expecting ',' delimiter: line 88 column 2 (char 3430)
Error processing NCT NCT02034019_inc: Extra data: line 47 column 1 (char 1096)
Error processing NCT NCT02419378_exc: Expecting ',' delimiter: line 28 column 13 (char 986)
Error processing NCT NCT00586898_exc: Extra data: line 28 column 2 (char 559)
Error processing NCT NCT00445029_exc: Expecting ',' delimiter: line 119 column 2 (char 4343)
Error processing NCT NCT01709981_exc: Extra data: line 92 column 1 (char 3971)
Error processing NCT NCT02432404_exc: Extra data: line 71 column 1 (char 1860)
Error processing NCT NCT00749112_inc: Extra data: line 86 column 1 (char 2538)
Error processing NCT NCT01491763_exc: Extra data: line 66 column 1 (char 1520)
Error processing NCT NCT00894712_inc: Expecting ',' delimiter: line 79 column 2 (char 2972)
Error processing NCT NCT00917891_exc: Expecting ',' delimiter: line 83 column 2 (char 3629)
Error processing NCT NCT01932996_inc: Extra data: line 58 column 3 (char 1479)
Error processing NCT NCT00391690_exc: Expecting ',' delimiter: line 98 column 2 (char 3565)
Error processing NCT NCT02301962_inc: Expecting ',' delimiter: line 50 column 2 (char 1607)
Error processing NCT NCT02385448_inc: Extra data: line 86 column 1 (char 2419)
Error processing NCT NCT00426751_inc: Expecting ',' delimiter: line 22 column 75 (char 568)
Error processing NCT NCT02579928_inc: Expecting ',' delimiter: line 81 column 2 (char 2956)
Error processing NCT NCT02425774_exc: Expecting ',' delimiter: line 47 column 122 (char 1248)
Error processing NCT NCT02441179_inc: Expecting ',' delimiter: line 25 column 71 (char 678)
Error processing NCT NCT02225548_inc: Extra data: line 65 column 1 (char 1788)
Error processing NCT NCT01322464_exc: Expecting ',' delimiter: line 91 column 2 (char 2942)
Error processing NCT NCT01261832_exc: Expecting ',' delimiter: line 90 column 2 (char 2515)
Error processing NCT NCT00543712_exc: Extra data: line 65 column 1 (char 1720)
Error processing NCT NCT02332291_exc: Expecting ',' delimiter: line 104 column 2 (char 3443)
Error processing NCT NCT02426944_exc: Extra data: line 117 column 1 (char 5645)
Error processing NCT NCT01490034_inc: Extra data: line 87 column 1 (char 2137)
Error processing NCT NCT01895946_exc: Expecting ',' delimiter: line 109 column 2 (char 3280)
Error processing NCT NCT01978028_exc: Invalid control character at: line 21 column 29 (char 434)
Error processing NCT NCT00050349_exc: Expecting ',' delimiter: line 84 column 2 (char 2801)
Error processing NCT NCT02570321_exc: Extra data: line 101 column 1 (char 2740)
Error processing NCT NCT02318446_inc: Extra data: line 71 column 1 (char 2178)
Error processing NCT NCT02526823_inc: Extra data: line 109 column 9 (char 3223)
Error processing NCT NCT02429583_inc: Extra data: line 47 column 1 (char 1069)
Error processing NCT NCT01701219_exc: Expecting ',' delimiter: line 71 column 2 (char 2176)
Error processing NCT NCT01680081_exc: Expecting ',' delimiter: line 24 column 82 (char 579)
Error processing NCT NCT00344318_exc: Expecting ',' delimiter: line 60 column 2 (char 2436)
Error processing NCT NCT02525991_inc: Expecting ',' delimiter: line 52 column 2 (char 1675)
Error processing NCT NCT02431559_exc: Expecting ',' delimiter: line 37 column 2 (char 1893)
Error processing NCT NCT02339844_inc: Extra data: line 94 column 1 (char 2408)
Error processing NCT NCT02167022_inc: Expecting ',' delimiter: line 9 column 182 (char 323)
Error processing NCT NCT01116973_exc: Expecting ',' delimiter: line 100 column 2 (char 2840)
Error processing NCT NCT00397215_exc: Expecting ',' delimiter: line 62 column 2 (char 2390)
Error processing NCT NCT01959425_exc: Expecting ',' delimiter: line 77 column 2 (char 2574)
Error processing NCT NCT02348918_inc: Expecting ',' delimiter: line 82 column 2 (char 2707)
Error processing NCT NCT02348918_exc: Extra data: line 62 column 1 (char 1915)
Error processing NCT NCT00679341_inc: Expecting ',' delimiter: line 98 column 2 (char 2855)
Error processing NCT NCT01890759_exc: Extra data: line 44 column 1 (char 1797)
Error processing NCT NCT02515773_inc: Expecting ',' delimiter: line 59 column 2 (char 2116)
Error processing NCT NCT00425789_inc: Extra data: line 58 column 1 (char 1363)
Error processing NCT NCT01815580_exc: Expecting ',' delimiter: line 82 column 2 (char 2485)
Error processing NCT NCT00943865_inc: Extra data: line 130 column 1 (char 4202)
Error processing NCT NCT02316886_exc: Expecting ',' delimiter: line 84 column 2 (char 2876)
Error processing NCT NCT02034019_exc: Expecting ',' delimiter: line 9 column 44 (char 253)
Error processing NCT NCT02068365_inc: Extra data: line 98 column 1 (char 2520)
Error processing NCT NCT01410890_inc: Expecting ',' delimiter: line 75 column 2 (char 2634)
Error processing NCT NCT02546856_inc: Expecting ',' delimiter: line 6 column 38 (char 97)
Error processing NCT NCT00846703_exc: Extra data: line 50 column 1 (char 1283)
Error processing NCT NCT02284737_exc: Expecting ',' delimiter: line 106 column 2 (char 3026)
Error processing NCT NCT02015923_exc: Extra data: line 25 column 1 (char 497)
Error processing NCT NCT00609531_exc: Expecting ',' delimiter: line 70 column 2 (char 2102)
Error processing NCT NCT00846703_inc: Expecting ',' delimiter: line 103 column 2 (char 4168)
Error processing NCT NCT02595190_inc: Expecting ',' delimiter: line 113 column 2 (char 4051)
Error processing NCT NCT01000155_exc: Expecting ',' delimiter: line 84 column 2 (char 2667)
Error processing NCT NCT01807897_exc: Extra data: line 83 column 1 (char 2732)
Error processing NCT NCT02371200_inc: Extra data: line 81 column 1 (char 2003)
Error processing NCT NCT02022709_inc: Extra data: line 81 column 1 (char 1995)
Error processing NCT NCT01799681_inc: Extra data: line 54 column 1 (char 1342)
Error processing NCT NCT02609048_exc: Extra data: line 110 column 1 (char 5271)
Error processing NCT NCT02195024_exc: Expecting ',' delimiter: line 93 column 2 (char 2879)
Error processing NCT NCT02396420_exc: Extra data: line 111 column 7 (char 3408)
Error processing NCT NCT02526823_exc: Extra data: line 69 column 1 (char 2134)
Error processing NCT NCT02609048_inc: Extra data: line 94 column 1 (char 2694)
Error processing NCT NCT02429765_inc: Expecting ',' delimiter: line 37 column 52 (char 1112)
Error processing NCT NCT02141061_inc: Expecting ',' delimiter: line 73 column 2 (char 2504)
Error processing NCT NCT01891383_inc: Extra data: line 92 column 3 (char 3020)

In [44]:
df_success = pd.DataFrame(success_data).set_index('NCT')
df_success.to_csv(eval_path+f'/{model}_eval.csv')

df_success

,label_AND,label_OR,label_NOT,label_DEPTH,model_AND,model_OR,model_NOT,model_DEPTH,diff_AND,diff_OR,diff_NOT,diff_DEPTH
NCT,,,,,,,,,,,,
NCT02042287_inc,9,0,0,19,7,4,4,13,-1,1,1,-1
NCT00440245_inc,1,1,0,5,0,1,0,3,-1,0,0,-1
NCT01963754_inc,8,1,1,17,8,2,0,17,0,1,-1,0
NCT02394158_inc,4,0,0,9,2,2,0,9,-1,1,0,0
NCT02303171_exc,3,0,0,7,2,2,0,7,-1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
NCT02579733_inc,4,0,1,7,5,1,0,7,1,1,-1,0
NCT01424020_exc,4,1,0,9,1,3,0,9,-1,1,0,0
NCT02537899_inc,5,1,0,11,6,2,0,11,1,1,0,0
NCT02364648_inc,2,0,0,5,1,2,0,7,-1,1,0,1
NCT02112734_exc,3,3,0,11,2,2,0,7,-1,-1,0,-1

In [45]:
true_values = df_success[['label_AND', 'label_OR', 'label_NOT', 'label_DEPTH']].values
predicted_values = df_success[['model_AND', 'model_OR', 'model_NOT', 'model_DEPTH']].values

metrics = {}
for i, metric in enumerate(['AND', 'OR', 'NOT', 'DEPTH']):
    y_true = true_values[:, i]
    y_pred = predicted_values[:, i]

    diffs = y_pred - y_true
    pct_greater = (diffs > 0).sum() / len(diffs) * 100
    pct_less = (diffs < 0).sum() / len(diffs) * 100
    pct_equal = (diffs == 0).sum() / len(diffs) * 100


    metrics[metric] = {
        'accuracy': round(accuracy_score(y_true, y_pred), 3),
        'precision': round(precision_score(y_true, y_pred, average='weighted', zero_division=0), 3),
        'recall': round(recall_score(y_true, y_pred, average='weighted', zero_division=0), 3),
        'f1_score': round(f1_score(y_true, y_pred, average='weighted', zero_division=0), 3),
        'pct_greater': round(pct_greater, 2),
        'pct_less': round(pct_less, 2),
        'pct_equal': round(pct_equal, 2)
       # 'confusion_matrix': confusion_matrix(y_true, y_pred)
    }
    metrics_df = pd.DataFrame(metrics).T  
    num_nct_files = len(df_success)
    metrics_df['num_nct_files'] = num_nct_files
    metrics_df['model_name'] = model
    # Save Metrics to CSV
    metrics_df.to_csv(os.path.join(eval_path, f'{model}_metrics_summary.csv'))

print(f"{len(df_success)} Daten mit {model}")
for metric, values in metrics.items():
    print(f"Metrics for {metric}:")
    print(f"  Accuracy: {values['accuracy']}")
    print(f"  Precision: {values['precision']}")
    print(f"  Recall: {values['recall']}")
    print(f"  F1 Score: {values['f1_score']}")

    print(f"  % Greater: {values['pct_greater']}")
    print(f"  % Less: {values['pct_less']}")
    print(f"  % Equal: {values['pct_equal']}")
    print()
    #print(f"  Confusion Matrix:\n{values['confusion_matrix']}\n")

760 Daten mit Llama-3-8B-Instruct_5_shot
Metrics for AND:
  Accuracy: 0.145
  Precision: 0.126
  Recall: 0.145
  F1 Score: 0.128
  % Greater: 22.24
  % Less: 63.29
  % Equal: 14.47

Metrics for OR:
  Accuracy: 0.2
  Precision: 0.33
  Recall: 0.2
  F1 Score: 0.226
  % Greater: 60.0
  % Less: 20.0
  % Equal: 20.0

Metrics for NOT:
  Accuracy: 0.782
  Precision: 0.731
  Recall: 0.782
  F1 Score: 0.75
  % Greater: 5.53
  % Less: 16.32
  % Equal: 78.16

Metrics for DEPTH:
  Accuracy: 0.195
  Precision: 0.201
  Recall: 0.195
  F1 Score: 0.19
  % Greater: 28.29
  % Less: 52.24
  % Equal: 19.47

In [46]:
matching_rows = df_success[df_success['label_AND'] == df_success['model_AND']][['label_AND', 'model_AND']]
matching_rows

                 label_AND  model_AND
NCT
NCT01963754_inc          8          8
NCT00959569_inc          3          3
NCT02456532_exc          2          2
NCT02019160_exc          1          1
NCT01650792_exc          7          7
...                    ...        ...
NCT00609531_inc          8          8
NCT02277067_exc          3          3
NCT02563535_inc          4          4
NCT02092467_inc          3          3
NCT00182520_inc          5          5

[110 rows x 2 columns]