In [7]:
import json
import os
import pandas as pd
import re
import shutil
from collections import defaultdict
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from functions import *

In [8]:
def find_folders_with_output(directory):
    folders_with_output = []
    for root, dirs, files in os.walk(directory):
        if 'output' in dirs:
            folders_with_output.append(root.split('\\')[1])
            dirs.remove('output')
    return folders_with_output

# Hauptordner, der durchsucht werden soll
main_directory = 'model_output'


models = find_folders_with_output(main_directory)
models

['Llama-3-70B-Instruct_3_shot',
 'Llama-3-70B-Instruct_5_shot',
 'Llama-3-8B-Instruct-Gradient-1048k_10_shot',
 'Llama-3-8B-Instruct-Gradient-1048k_20_shot',
 'Llama-3-8B-Instruct_3_shot',
 'Llama-3-8B-Instruct_4_shot',
 'Llama-3-8B-Instruct_5_shot']

In [9]:
save = True

### Model Output to nice JSON and Failure

In [10]:
def process_files(model, save=save):
    input_dir = f"model_output/{model}/output/"
    output_dir = f"model_output/{model}/formatted/"
    failure_dir = f"model_output/{model}/failed/"
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(failure_dir, exist_ok=True)
    for filename in os.listdir(input_dir):
        if filename.endswith('.json'):
            input_file_path = os.path.join(input_dir, filename)
            output_file_path = os.path.join(output_dir, filename)
            failure_file_path = os.path.join(failure_dir, filename)
            try:
                file = read_json(input_file_path)
                print(f"Processing file: {filename}")
                if save:
                    save_json_to_file(file, output_file_path)
            except Exception as e:
                print(f"Error processing file {filename}: {e}")
                if save:
                    shutil.move(input_file_path, failure_file_path)

In [11]:
def extract_nct_number(filename):
    parts = filename.split('_')
    nct_number = None
    file_type = None
    for part in parts:
        if part.startswith("NCT"):
            nct_number = part
        if part in ["inc", "exc"]:
            file_type = part
    return nct_number+"_"+file_type


def extract_logical_structure(data):
    structure = defaultdict(int)
    def traverse(node, depth=0):
        nonlocal structure
        structure["depth"] = max(structure["depth"], depth)

        if isinstance(node, dict):
            for key in node:
                if key in ["AND", "OR", "NOT"]:
                    structure[key] += 1
                traverse(node[key], depth + 1)
        elif isinstance(node, list):
            for item in node:
                traverse(item, depth + 1)

    traverse(data)
    return dict(structure)

def extract_raw_texts(data):
    raw_texts = set()
    def traverse(node):
        if isinstance(node, dict):
            for key, value in node.items():
                if key == "raw_text":
                    raw_texts.add(value)
                else:
                    traverse(value)
        elif isinstance(node, list):
            for item in node:
                traverse(item)

    traverse(data)
    return raw_texts

def extract_words(raw_texts):
    words = set()
    for text in raw_texts:
        words.update(text.split())
    return words

In [12]:
for model in models:
    # 1 - Preprocess Files
    process_files(model, save=save)
    
    # 2 - Evaluate Files
    p2_label_path = "chia_label/p2"
    ready_path = f"model_output/{model}/ready"
    failed_model_path = f"model_output/{model}/failed_inner"
    p2_model_formatted_path = f"model_output/{model}/formatted"
    eval_path = f"evaluate/batch1"
    for path in [ready_path, failed_model_path, p2_model_formatted_path]:
        os.makedirs(path, exist_ok=True)
    
    label_files = {extract_nct_number(f): os.path.join(p2_label_path, f) for f in os.listdir(p2_label_path) if f.endswith('.json')}
    model_files = {extract_nct_number(f): os.path.join(p2_model_formatted_path, f) for f in os.listdir(p2_model_formatted_path) if f.endswith('.json')}
    
    common_ncts = set(label_files.keys()).intersection(model_files.keys())
    labels = []
    predictions = []
    success_data = []
    
    for nct in common_ncts:
        try:
            label_data = read_json(label_files[nct])
            model_data = read_json(model_files[nct])
            label_structure = extract_logical_structure(label_data)
            model_structure = extract_logical_structure(model_data)
    
            # Try count words
            label_raw_texts = extract_raw_texts(label_data)
            model_raw_texts = extract_raw_texts(model_data)
            
            missing_texts = label_raw_texts - model_raw_texts
            
            label_words = extract_words(label_raw_texts)
            model_words = extract_words(model_raw_texts)
            missing_words = label_words - model_words
            missing_words_pct = len(missing_words) / len(label_words) * 100 if label_words else 0
            print(f"Processing NCT {nct}")
            print(round(missing_words_pct,2), "%")
            print(label_words.issubset(model_words))
            print("Label Text \n")
            print(label_words)
            print("\nModel Text \n")
            print(model_words)
            print()
            
            success_data.append({
                'NCT': nct,
                'label_AND': label_structure.get('AND', 0),
                'label_OR': label_structure.get('OR', 0),
                'label_NOT': label_structure.get('NOT', 0),
                'label_DEPTH': label_structure.get('depth', 0),
                'model_AND': model_structure.get('AND', 0),
                'model_OR': model_structure.get('OR', 0),
                'model_NOT': model_structure.get('NOT', 0),
                'model_DEPTH': model_structure.get('depth', 0),
                'diff_AND': 1 if model_structure.get('AND', 0) > label_structure.get('AND', 0) else -1 if model_structure.get('AND', 0) < label_structure.get('AND', 0) else 0,
                'diff_OR': 1 if model_structure.get('OR', 0) > label_structure.get('OR', 0) else -1 if model_structure.get('OR', 0) < label_structure.get('OR', 0) else 0,
                'diff_NOT': 1 if model_structure.get('NOT', 0) > label_structure.get('NOT', 0) else -1 if model_structure.get('NOT', 0) < label_structure.get('NOT', 0) else 0,
                'diff_DEPTH': 1 if model_structure.get('depth', 0) > label_structure.get('depth', 0) else -1 if model_structure.get('depth', 0) < label_structure.get('depth', 0) else 0
                
            })
    
            labels.append(label_structure)
            predictions.append(model_structure)
            save and shutil.copy(model_files[nct], os.path.join(ready_path, os.path.basename(model_files[nct])))
        except Exception as e:
            #print(f"Error processing NCT {nct}: {e}")
            save and shutil.copy(model_files[nct], os.path.join(failed_model_path, os.path.basename(model_files[nct])))
    
    df_success = pd.DataFrame(success_data).set_index('NCT')
    df_success.to_csv(eval_path+f'/{model}_eval.csv')
    true_values = df_success[['label_AND', 'label_OR', 'label_NOT', 'label_DEPTH']].values
    predicted_values = df_success[['model_AND', 'model_OR', 'model_NOT', 'model_DEPTH']].values
    
    metrics = {}
    for i, metric in enumerate(['AND', 'OR', 'NOT', 'DEPTH']):
        y_true = true_values[:, i]
        y_pred = predicted_values[:, i]
    
        diffs = y_pred - y_true
        pct_greater = (diffs > 0).sum() / len(diffs) * 100
        pct_less = (diffs < 0).sum() / len(diffs) * 100
        pct_equal = (diffs == 0).sum() / len(diffs) * 100
    
        metrics[metric] = {
            'accuracy': round(accuracy_score(y_true, y_pred), 3),
            'precision': round(precision_score(y_true, y_pred, average='weighted', zero_division=0), 3),
            'recall': round(recall_score(y_true, y_pred, average='weighted', zero_division=0), 3),
            'f1_score': round(f1_score(y_true, y_pred, average='weighted', zero_division=0), 3),
            'pct_greater': round(pct_greater, 2),
            'pct_less': round(pct_less, 2),
            'pct_equal': round(pct_equal, 2)
            # 'confusion_matrix': confusion_matrix(y_true, y_pred)
        }
        metrics_df = pd.DataFrame(metrics).T
        num_nct_files = len(df_success)
        metrics_df['num_nct_files'] = num_nct_files
        metrics_df['model_name'] = model
        # Save Metrics to CSV
        metrics_df.to_csv(os.path.join(eval_path, f'{model}_metrics_summary.csv'))

Processing file: Llama-3-70B-Instruct_NCT00050349_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00050349_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00061308_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00094861_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00094861_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00122070_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00122070_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00182520_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00182520_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00183885_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00183885_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00198913_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00198913_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00235170_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00235170_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00236340_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00236340_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00250640_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00250640_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00279552_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00279552_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00305097_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00305097_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00312429_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00312429_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00317148_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00317148_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00319748_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00319748_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00324363_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00324363_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00343668_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00343668_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00344318_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00344318_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00351611_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00351611_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00356148_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00356148_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00379366_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00379366_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00391690_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00391690_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00396734_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00396734_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00397215_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00397215_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00401245_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00401245_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00404495_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00404495_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00425789_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00425789_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00426751_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00426751_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00440245_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00440245_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00445029_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00445029_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00455663_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00455663_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00461136_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00480129_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00480129_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00483106_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00500500_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00500500_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00502567_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00502567_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00527826_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00527826_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00543712_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00543712_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00576173_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00576173_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00586898_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00586898_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00599924_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00599924_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00609531_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00609531_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00625742_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00625742_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00639795_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00639795_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00650312_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00650312_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00676273_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00676273_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00679341_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00679341_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00718952_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00718952_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00720031_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00720031_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00728156_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00728156_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00730301_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00730301_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00749112_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00749112_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00752310_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00752310_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00785213_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00785213_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00787254_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00787254_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00806273_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00806273_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00806936_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00806936_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00812344_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00812344_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00846703_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00846703_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00862446_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00862446_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00867958_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00867958_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00886158_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00886158_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00894712_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00894712_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00904202_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00904202_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00917891_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00917891_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00926523_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00926523_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00931983_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00931983_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00943865_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00943865_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00954850_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00954850_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00959569_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00959569_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00962364_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00965900_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00965900_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00970866_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00970866_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00989261_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00989261_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00994786_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT00994786_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01000155_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01000155_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01009359_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01009359_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01032109_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01032109_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01051414_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01051414_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01064752_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01064752_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01078051_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01078051_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01082549_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01082549_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01084993_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01084993_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01088750_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01088750_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01098383_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01098383_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01116882_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01116882_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01116973_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01116973_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01117181_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01117181_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01118871_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01118871_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01175044_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01175044_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01177891_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01177891_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01184638_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01184638_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01205334_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01205334_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01214096_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01214096_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01217671_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01217671_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01218737_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01218737_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01228279_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01228279_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01236417_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01236417_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01261832_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01261832_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01312012_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01312012_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01313676_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01313676_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01314898_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01314898_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01320579_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01320579_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01322464_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01322464_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01346436_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01346436_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01349413_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01349413_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01352598_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01373684_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01373684_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01391780_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01391780_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01401335_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01401335_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01410890_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01410890_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01424020_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01424020_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01440296_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01446094_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01446094_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01483118_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01483118_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01490034_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01491295_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01491295_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01491763_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01491763_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01497639_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01497639_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01501201_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01501201_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01518946_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01518946_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01531257_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01531257_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01567605_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01567605_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01579604_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01579604_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01581749_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01581749_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01602081_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01604187_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01604187_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01614041_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01614041_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01630954_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01631058_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01631058_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01639664_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01639664_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01642875_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01642875_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01650792_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01650792_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01664507_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01664507_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01665417_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01665417_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01669369_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01669369_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01680081_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01680081_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01684501_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01684501_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01696617_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01696617_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01700790_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01701219_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01701219_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01709981_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01709981_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01711801_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01711801_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01715584_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01715584_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01715714_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01715714_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01717911_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01717911_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01720394_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01720394_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01728194_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01728194_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01735955_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01735955_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01742117_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01742117_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01743755_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01743755_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01757717_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01757717_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01765231_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01765231_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01768195_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01768195_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01770340_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01770340_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01774019_exc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01774019_inc_3_shot.json
Processing file: Llama-3-70B-Instruct_NCT01793519_exc_3_shot.json

KeyboardInterrupt:

In [ ]:
# NCT02935855_inc

In [10]:
df_success = pd.DataFrame(success_data).set_index('NCT')
df_success.to_csv(eval_path+f'/{model}_eval.csv')

df_success

,label_AND,label_OR,label_NOT,label_DEPTH,model_AND,model_OR,model_NOT,model_DEPTH,diff_AND,diff_OR,diff_NOT,diff_DEPTH
NCT,,,,,,,,,,,,
NCT02966236_inc,2,0,0,5,1,0,0,3,-1,0,0,-1
NCT02566226_exc,6,0,0,11,1,4,0,11,-1,1,0,0
NCT02933671_inc,3,0,0,7,3,1,0,8,0,1,0,1
NCT02816164_inc,4,6,0,17,5,1,0,13,1,-1,0,-1
NCT01944800_exc,1,0,0,3,1,1,0,5,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
NCT01631058_exc,3,2,0,9,1,2,0,7,-1,0,0,-1
NCT02200978_exc,1,3,0,9,1,1,0,5,0,-1,0,-1
NCT02469610_exc,1,0,0,3,1,0,0,3,0,0,0,0
NCT02859480_inc,2,0,0,5,1,0,0,3,-1,0,0,-1
NCT01491295_exc,3,5,0,9,2,1,0,5,-1,-1,0,-1

In [11]:
true_values = df_success[['label_AND', 'label_OR', 'label_NOT', 'label_DEPTH']].values
predicted_values = df_success[['model_AND', 'model_OR', 'model_NOT', 'model_DEPTH']].values

metrics = {}
for i, metric in enumerate(['AND', 'OR', 'NOT', 'DEPTH']):
    y_true = true_values[:, i]
    y_pred = predicted_values[:, i]

    diffs = y_pred - y_true
    pct_greater = (diffs > 0).sum() / len(diffs) * 100
    pct_less = (diffs < 0).sum() / len(diffs) * 100
    pct_equal = (diffs == 0).sum() / len(diffs) * 100


    metrics[metric] = {
        'accuracy': round(accuracy_score(y_true, y_pred), 3),
        'precision': round(precision_score(y_true, y_pred, average='weighted', zero_division=0), 3),
        'recall': round(recall_score(y_true, y_pred, average='weighted', zero_division=0), 3),
        'f1_score': round(f1_score(y_true, y_pred, average='weighted', zero_division=0), 3),
        'pct_greater': round(pct_greater, 2),
        'pct_less': round(pct_less, 2),
        'pct_equal': round(pct_equal, 2)
       # 'confusion_matrix': confusion_matrix(y_true, y_pred)
    }
    metrics_df = pd.DataFrame(metrics).T  
    num_nct_files = len(df_success)
    metrics_df['num_nct_files'] = num_nct_files
    metrics_df['model_name'] = model
    # Save Metrics to CSV
    metrics_df.to_csv(os.path.join(eval_path, f'{model}_metrics_summary.csv'))

print(f"{len(df_success)} Daten mit {model}")
for metric, values in metrics.items():
    print(f"Metrics for {metric}:")
    print(f"  Accuracy: {values['accuracy']}")
    print(f"  Precision: {values['precision']}")
    print(f"  Recall: {values['recall']}")
    print(f"  F1 Score: {values['f1_score']}")

    print(f"  % Greater: {values['pct_greater']}")
    print(f"  % Less: {values['pct_less']}")
    print(f"  % Equal: {values['pct_equal']}")
    print()
    #print(f"  Confusion Matrix:\n{values['confusion_matrix']}\n")

1032 Daten mit Llama-3-8B-Instruct-Gradient-1048k_10_shot
Metrics for AND:
  Accuracy: 0.254
  Precision: 0.211
  Recall: 0.254
  F1 Score: 0.188
  % Greater: 6.78
  % Less: 67.83
  % Equal: 25.39

Metrics for OR:
  Accuracy: 0.304
  Precision: 0.416
  Recall: 0.304
  F1 Score: 0.342
  % Greater: 48.06
  % Less: 21.51
  % Equal: 30.43

Metrics for NOT:
  Accuracy: 0.859
  Precision: 0.737
  Recall: 0.859
  F1 Score: 0.793
  % Greater: 0.0
  % Less: 14.15
  % Equal: 85.85

Metrics for DEPTH:
  Accuracy: 0.277
  Precision: 0.315
  Recall: 0.277
  F1 Score: 0.284
  % Greater: 32.56
  % Less: 39.73
  % Equal: 27.71

In [12]:
matching_rows = df_success[df_success['label_AND'] == df_success['model_AND']][['label_AND', 'model_AND']]
matching_rows

                 label_AND  model_AND
NCT
NCT02933671_inc          3          3
NCT01944800_exc          1          1
NCT02566863_inc          2          2
NCT02456532_inc          1          1
NCT01236417_inc          4          4
...                    ...        ...
NCT02323399_exc          1          1
NCT03012984_inc          5          5
NCT01184638_inc          2          2
NCT02200978_exc          1          1
NCT02469610_exc          1          1

[262 rows x 2 columns]